In [40]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score

theCsv["avg_bottle_dist_dim0"] =theCsv5["avg_bottle_dist_dim0"]
theCsv["sd_bottle_dist_dim0"] =theCsv5["sd_bottle_dist_dim0"]


#theCsv["avg_bottle_dist_dim0"] =theCsv6["avg_bottle_dist_dim0"]
#theCsv["sd_bottle_dist_dim0"] =theCsv6["sd_bottle_dist_dim0"]

theCsv["avg_bottle_dist_dim0"] =theCsv7["avg_bottle_dist_dim0"]
theCsv["sd_bottle_dist_dim0"] =theCsv7["sd_bottle_dist_dim0"]
118

['N', 'R', 'R', 'N', 'N', 'AF', 'N', 'R', 'N', 'AF', 'N', 'N', 'N', 'R', 'AF', 'AF', 'N', 'AF', 'N', 'N', 'N', 'R', 'R', 'R', 'AF', 'R', 'N', 'N', 'R', 'R', 'R', 'N', 'N', 'AF', 'N', 'R', 'N', 'R', 'R', 'AF', 'AF', 'N', 'R', 'R', 'N', 'N', 'R', 'N', 'N', 'R', 'AF', 'AF', 'N', 'R', 'R', 'AF', 'AF', 'N', 'N', 'N', 'N', 'N', 'AF', 'R', 'R', 'N', 'R', 'R', 'N', 'AF', 'AF', 'N', 'R', 'AF', 'R', 'R', 'AF', 'AF', 'R', 'R', 'AF', 'R', 'R', 'AF', 'N', 'N', 'N', 'AF', 'AF', 'AF', 'AF', 'R', 'N', 'AF', 'AF', 'AF', 'AF', 'N', 'R', 'N', 'N', 'AF', 'R', 'AF', 'N', 'R', 'N', 'AF', 'AF', 'R', 'N', 'R', 'R', 'R', 'AF', 'AF', 'AF', 'N', 'R', 'R', 'N', 'N', 'AF', 'R', 'N', 'N', 'R', 'AF', 'R', 'R', 'N', 'R', 'N', 'N', 'R', 'N', 'N', 'N', 'AF', 'N', 'N', 'AF', 'N', 'N', 'R', 'N', 'AF', 'R', 'N', 'N', 'R', 'R', 'AF', 'AF', 'R', 'AF', 'N', 'R', 'N', 'N', 'AF', 'AF', 'N', 'R', 'AF', 'N', 'AF', 'AF', 'R', 'AF', 'AF', 'AF', 'R', 'R', 'N', 'N', 'R', 'N', 'N', 'AF', 'N', 'AF', 'R', 'R', 'R', 'AF', 'AF', 'R', 'AF', 'AF', 'R', 'R', 'N', 'AF', 'R', 'AF', 'R', 'AF']

['N', 'R', 'R', 'N', 'N', 'AF', 'N', 'R', 'N', 'AF', 'N', 'N', 'N', 'R', 'AF', 'AF', 'N', 'AF', 'N', 'N', 'N', 'R', 'R', 'R', 'AF', 'R', 'N', 'N', 'R', 'R', 'R', 'N', 'N', 'AF', 'N', 'R', 'N', 'R', 'R', 'AF', 'AF', 'N', 'R', 'R', 'N', 'N', 'R', 'N', 'N', 'R', 'AF', 'AF', 'N', 'R', 'R', 'AF', 'AF', 'N', 'N', 'N', 'N', 'N', 'AF', 'R', 'R', 'N', 'R', 'R', 'N', 'AF', 'AF', 'N', 'R', 'AF', 'R', 'R', 'AF', 'AF', 'R', 'R', 'AF', 'R', 'R', 'AF', 'N', 'N', 'N', 'AF', 'AF', 'AF', 'AF', 'R', 'N', 'AF', 'AF', 'AF', 'AF', 'N', 'R', 'N', 'N', 'AF', 'R', 'AF', 'N', 'R', 'N', 'AF', 'AF', 'R', 'N', 'R', 'R', 'R', 'AF', 'AF', 'AF', 'N', 'R', 'R', 'N', 'N', 'AF', 'R', 'N', 'N', 'R', 'AF', 'R', 'R', 'N', 'R', 'N', 'N', 'R', 'N', 'N', 'N', 'AF', 'N', 'N', 'AF', 'N', 'N', 'R', 'N', 'AF', 'R', 'N', 'N', 'R', 'R', 'AF', 'AF', 'R', 'AF', 'N', 'R', 'N', 'N', 'AF', 'AF', 'N', 'R', 'AF', 'N', 'AF', 'AF', 'R', 'AF', 'AF', 'AF', 'R', 'R', 'N', 'N', 'R', 'N', 'N', 'AF', 'N', 'AF', 'R', 'R', 'R', 'AF', 'AF', 'R', 'AF', 'AF', 'R', 'R', 'N', 'AF', 'R', 'AF', 'R', 'AF']


In [41]:
theTotal = []
classDict = {}
lineCount = 0

x = open("200_set_of_Norm_AF_Rand.csv")
for line in x:
    line = line.strip()
    #print(line)
    a,b,c,d = line.split(",")
    if(lineCount != 0):
            #normalListTrain.append(b)
            theTotal.append(b)
            classDict[b] = ["N"]
            #normalListTest.append(b)
            #AFListTrain.append(c)
            theTotal.append(c)
            classDict[c] = ["AF"]
            #AFListTest.append(c)
            #randomListTest.append(d)
            theTotal.append(d)
            classDict["d"] = ["R"]
    lineCount += 1

            
theFrame = {"mean":[],"std_dev":[],"theClass":[]}

theCsv = pd.read_csv("Reduced_Pers_Mean_sd_dimension_0.csv", index_col=0)
theCsv2 = pd.read_csv("Reduced_Pers_Mean_sd_dimension_1.csv",index_col=0)
theCsv3 = pd.read_csv("Reduced_Pers_Mean_sd_dimension_2.csv",index_col=0)
theCsv4 = pd.read_csv("Reduced_Pers_Lifetimes_dim_0_1_2.csv",index_col=0)
theCsv5 = pd.read_csv("reduced_bottleneck_ave_sd_dim0.csv",index_col=0)
theCsv6 = pd.read_csv("reduced_bottleneck_ave_sd_dist_dim1.csv",index_col=0)
theCsv7 = pd.read_csv("reduced_bottleneck_ave_sd_dist_dim2.csv",index_col=0)
theCsv8 = pd.read_csv("number_of_births_deaths_dim0.csv",index_col=0)
theCsv9 = pd.read_csv("number_of_births_deaths_dim1.csv",index_col=0)
theCsv10 = pd.read_csv("number_of_births_deaths_dim2.csv",index_col=0)
theCsv11 = pd.read_csv("skewness_birth_dim12.csv",index_col=0)
theCsv12 = pd.read_csv("skewness_death_dim012.csv",index_col=0)
theCsv13 = pd.read_csv("kurtosis_birth_dim12.csv",index_col=0)
theCsv14 = pd.read_csv("kurtosis_death_dim012.csv",index_col=0)
#theCsv8 = pd.read_csv("reduced_bottleneck_ave_sd_dist_dim2.csv",index_col=0)
#bigData = theCsv.append(theCsv2, ignore_index=True)

#print(bigData)

aList = []
aList2 = []
aList3 = []
for i in range(0,200):
    aList.append("N")
    aList2.append(0)
    aList3.append(0)

for i in range(0,200):
    aList.append("AF")
    aList2.append(1)
    aList3.append(0)
    
for i in range(0,200):
    aList.append("R")
    aList2.append(0)
    aList3.append(1)

#theCsv["Normal"] = np.asarray(aList)
#theCsv["AF"] = np.asarray(aList2)
#theCsv["Random"] = np.asarray(aList3)
#### make dataframe 
###
#bigData  

In [42]:
#theCsv

In [43]:
#theCsv2.loc[599] =[0,0,0,0]
#theCsv2.loc[600] =[0,0,0,0]
#theCsv2
#bigdata = pd.concat([theCsv, theCsv2])

theCsv["Means_dim1_birth"] = theCsv2["Means_dim1_birth"]
theCsv["Means_dim1_death"] = theCsv2["Means_dim1_birth"]
theCsv["sd_dim1_birth"] = theCsv2["sd_dim1_birth"]
theCsv["sd_dim1_death"] =theCsv2["sd_dim1_death"]

theCsv["Means_dim2_birth"] = theCsv3["Means_dim2_birth"]
theCsv["Means_dim2_death"] = theCsv3["Means_dim2_birth"]
theCsv["sd_dim2_birth"] = theCsv3["sd_dim2_birth"]
theCsv["sd_dim2_death"] =theCsv3["sd_dim2_death"]

#theCsv["Means_dim0_birth"] = theCsv4["Means_dim0_birth"]
#theCsv["Means_dim0_death"] = theCsv4["Means_dim0_birth"]
#theCsv["sd_dim0_birth"] = theCsv4["sd_dim0_birth"]
#theCsv["sd_dim0_death"] =theCsv4["sd_dim0_death"]

theCsv["Lifetime_dim0"] = theCsv4["Lifetime_dim0"]
theCsv["Lifetime_dim1"] = theCsv4["Lifetime_dim1"]
theCsv["Lifetime_dim2"] =theCsv4["Lifetime_dim2"]


theCsv["avg_bottle_dist_dim0"] =theCsv5["V1"]
theCsv["sd_bottle_dist_dim0"] =theCsv5["V2"]


theCsv["avg_bottle_dist_dim1"] =theCsv6["V1"]
theCsv["sd_bottle_dist_dim1"] =theCsv6["V2"]

theCsv["avg_bottle_dist_dim2"] =theCsv7["V1"]
theCsv["sd_bottle_dist_dim2"] =theCsv7["V2"]

theCsv["num_dim0"] = theCsv8["x"]
#theCsv["num_dim1"] = theCsv9["x"]
theCsv["num_dim2"] = theCsv10["x"]

#theCsv["num_dim1"] = theCsv10["x"]

theCsv["skew_death1"] =theCsv12["skew.death.dim1"]
theCsv["skew_death2"] =theCsv12["skew.death.dim2"]
#theCsv["skew_death0"] =theCsv12["skew.death.dim0"]


theCsv["skew_birth1"] = theCsv11["skew.birth.dim1"]
#theCsv["skew_birth2"] = theCsv11["skew.birth.dim2"]

#theCsv["katorsis1"] =theCsv14["kurt.death.dim1"]
theCsv["katorsis2"] =theCsv14["kurt.death.dim2"]
theCsv["katorsis0"] =theCsv14["kurt.death.dim0"]


#theCsv["katorsisBirth1"] = theCsv13["kurt.birth.dim1"]
#theCsv["katorsisBirth1"] = theCsv13["kurt.birth.dim2"]



print(theCsv)
#theCsv
#print(np.isnan(theCsv))
theCsv["Normal"] = np.asarray(aList)
#theCsv

#theCsv.fillna(theCsv.mean())

#print(np.where(theCsv.values >= np.finfo(np.float64).max))

     Means_dim0_birth  Means_dim0_death  sd_dim0_birth  sd_dim0_death  \
1                   0          0.598550              0       0.325249   
2                   0          0.769444              0       0.422174   
3                   0          0.422764              0       0.169927   
4                   0          0.329685              0       0.157529   
5                   0          0.444172              0       0.199625   
6                   0          0.415409              0       0.142401   
7                   0          0.487156              0       0.117997   
8                   0          0.223625              0       0.081608   
9                   0          0.835012              0       0.314351   
10                  0          0.876449              0       0.442794   
11                  0          0.245021              0       0.081972   
12                  0          0.537592              0       0.380163   
13                  0          0.313160            

In [44]:
### code from meduim torwards data scienec example
# Labels are the values we want to pred

labels = np.array(theCsv["Normal"])

# Remove the labels from the features
# axis 1 refers to the columns
theCsv = theCsv.drop('Normal', axis = 1)
#theCsv = theCsv.drop('AF', axis = 1)
#theCsv = theCsv.drop('Random', axis = 1)

# Saving feature names for later use
feature_list = list(theCsv.columns)

# Convert to numpy array
features = np.array(theCsv)


# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split


# Split the data into training and testing sets
train_features, test_features, train_labels, test_labels = train_test_split(theCsv, labels, test_size = 0.33, random_state = 42)


#print(test_labels.tolist())

In [45]:
# Import the model we are using
#from sklearn.ensemble import RandomForest
predict_list = []
# Instantiate model with 1000 decision trees
for i in range(0,300):
    #rf = RandomForestClassifier(bootstrap=True,max_depth=20,max_features="sqrt",min_samples_leaf=4,min_samples_split=10,n_estimators=50,random_state=118)
    rf = RandomForestClassifier(bootstrap=True,max_depth=20,max_features="sqrt",min_samples_leaf=4,min_samples_split=10,n_estimators=50,random_state=i)

# Train the model on training data
    rf.fit(train_features, train_labels)

    predictions = rf.predict(test_features)
    predict_list.append(predictions)

In [46]:
print(predictions)

['N' 'R' 'R' 'N' 'N' 'AF' 'R' 'R' 'N' 'AF' 'AF' 'N' 'R' 'R' 'AF' 'N' 'R'
 'AF' 'N' 'N' 'N' 'R' 'R' 'R' 'AF' 'R' 'AF' 'R' 'R' 'N' 'N' 'R' 'N' 'AF'
 'AF' 'R' 'N' 'R' 'R' 'AF' 'R' 'AF' 'R' 'R' 'R' 'N' 'R' 'N' 'N' 'AF' 'AF'
 'AF' 'N' 'R' 'N' 'AF' 'N' 'N' 'AF' 'AF' 'N' 'N' 'N' 'AF' 'R' 'R' 'R' 'R'
 'AF' 'AF' 'AF' 'N' 'N' 'AF' 'R' 'N' 'AF' 'AF' 'R' 'AF' 'N' 'R' 'AF' 'N'
 'N' 'N' 'AF' 'AF' 'AF' 'AF' 'R' 'AF' 'N' 'AF' 'N' 'AF' 'AF' 'N' 'R' 'N'
 'N' 'N' 'R' 'AF' 'R' 'N' 'AF' 'N' 'N' 'R' 'AF' 'R' 'R' 'R' 'AF' 'AF' 'AF'
 'R' 'N' 'R' 'AF' 'N' 'N' 'R' 'N' 'R' 'R' 'AF' 'R' 'R' 'N' 'R' 'R' 'AF' 'R'
 'N' 'AF' 'N' 'N' 'AF' 'AF' 'N' 'AF' 'R' 'R' 'AF' 'AF' 'R' 'AF' 'AF' 'R'
 'R' 'AF' 'AF' 'R' 'AF' 'N' 'R' 'N' 'R' 'R' 'AF' 'R' 'N' 'AF' 'N' 'N' 'N'
 'R' 'AF' 'N' 'N' 'R' 'R' 'AF' 'AF' 'R' 'AF' 'N' 'AF' 'AF' 'AF' 'R' 'R'
 'AF' 'AF' 'R' 'AF' 'N' 'N' 'R' 'R' 'N' 'AF' 'R' 'AF' 'R' 'N']


In [47]:
print(test_labels)

['N' 'R' 'R' 'N' 'N' 'AF' 'N' 'R' 'N' 'AF' 'N' 'N' 'N' 'R' 'AF' 'AF' 'N'
 'AF' 'N' 'N' 'N' 'R' 'R' 'R' 'AF' 'R' 'N' 'N' 'R' 'R' 'R' 'N' 'N' 'AF' 'N'
 'R' 'N' 'R' 'R' 'AF' 'AF' 'N' 'R' 'R' 'N' 'N' 'R' 'N' 'N' 'R' 'AF' 'AF'
 'N' 'R' 'R' 'AF' 'AF' 'N' 'N' 'N' 'N' 'N' 'AF' 'R' 'R' 'N' 'R' 'R' 'N'
 'AF' 'AF' 'N' 'R' 'AF' 'R' 'R' 'AF' 'AF' 'R' 'R' 'AF' 'R' 'R' 'AF' 'N' 'N'
 'N' 'AF' 'AF' 'AF' 'AF' 'R' 'N' 'AF' 'AF' 'AF' 'AF' 'N' 'R' 'N' 'N' 'AF'
 'R' 'AF' 'N' 'R' 'N' 'AF' 'AF' 'R' 'N' 'R' 'R' 'R' 'AF' 'AF' 'AF' 'N' 'R'
 'R' 'N' 'N' 'AF' 'R' 'N' 'N' 'R' 'AF' 'R' 'R' 'N' 'R' 'N' 'N' 'R' 'N' 'N'
 'N' 'AF' 'N' 'N' 'AF' 'N' 'N' 'R' 'N' 'AF' 'R' 'N' 'N' 'R' 'R' 'AF' 'AF'
 'R' 'AF' 'N' 'R' 'N' 'N' 'AF' 'AF' 'N' 'R' 'AF' 'N' 'AF' 'AF' 'R' 'AF'
 'AF' 'AF' 'R' 'R' 'N' 'N' 'R' 'N' 'N' 'AF' 'N' 'AF' 'R' 'R' 'R' 'AF' 'AF'
 'R' 'AF' 'AF' 'R' 'R' 'N' 'AF' 'R' 'AF' 'R' 'AF']


In [48]:
theMax = 0
for i in range(0,300):    
    if(accuracy_score(test_labels, predict_list[i]) > theMax):
        theMax = accuracy_score(test_labels, predict_list[i])
print(theMax)

0.636363636364


In [49]:
results = confusion_matrix(test_labels, predictions,labels=["AF", "N", "R"])
print(results)
np.average(f1_score(test_labels, predictions, average=None))

[[38 19  4]
 [23 34 14]
 [ 7  8 51]]


0.61995145250959205

In [50]:
#print('Parameters currently in use:\n')
#print(rf.get_params())

In [51]:
from sklearn.model_selection import RandomizedSearchCV

random_grid ={'bootstrap': [True, False],
 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, None],
 'max_features': ['auto', 'sqrt'],
 'min_samples_leaf': [1, 2, 4],
 'min_samples_split': [2, 5, 10],
 'n_estimators': [10,15,20,25,30,50,100,200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]}


rf = RandomForestClassifier()
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all available cores
#rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 500, cv = 3, verbose=2, random_state=42, n_jobs = -1)

# Fit the random search model
#rf_random.fit(train_features, train_labels)

#rf_random.best_params_

In [52]:
var1 = 36/(29+28)
var2 = 48/(31+39)
var3 = 112/(73+66)

print((var1+var2+var3)/3)

0.7076828762553866
