In [98]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score

theCsv["avg_bottle_dist_dim0"] =theCsv5["avg_bottle_dist_dim0"]
theCsv["sd_bottle_dist_dim0"] =theCsv5["sd_bottle_dist_dim0"]


#theCsv["avg_bottle_dist_dim0"] =theCsv6["avg_bottle_dist_dim0"]
#theCsv["sd_bottle_dist_dim0"] =theCsv6["sd_bottle_dist_dim0"]

theCsv["avg_bottle_dist_dim0"] =theCsv7["avg_bottle_dist_dim0"]
theCsv["sd_bottle_dist_dim0"] =theCsv7["sd_bottle_dist_dim0"]
118

['N', 'R', 'R', 'N', 'N', 'AF', 'N', 'R', 'N', 'AF', 'N', 'N', 'N', 'R', 'AF', 'AF', 'N', 'AF', 'N', 'N', 'N', 'R', 'R', 'R', 'AF', 'R', 'N', 'N', 'R', 'R', 'R', 'N', 'N', 'AF', 'N', 'R', 'N', 'R', 'R', 'AF', 'AF', 'N', 'R', 'R', 'N', 'N', 'R', 'N', 'N', 'R', 'AF', 'AF', 'N', 'R', 'R', 'AF', 'AF', 'N', 'N', 'N', 'N', 'N', 'AF', 'R', 'R', 'N', 'R', 'R', 'N', 'AF', 'AF', 'N', 'R', 'AF', 'R', 'R', 'AF', 'AF', 'R', 'R', 'AF', 'R', 'R', 'AF', 'N', 'N', 'N', 'AF', 'AF', 'AF', 'AF', 'R', 'N', 'AF', 'AF', 'AF', 'AF', 'N', 'R', 'N', 'N', 'AF', 'R', 'AF', 'N', 'R', 'N', 'AF', 'AF', 'R', 'N', 'R', 'R', 'R', 'AF', 'AF', 'AF', 'N', 'R', 'R', 'N', 'N', 'AF', 'R', 'N', 'N', 'R', 'AF', 'R', 'R', 'N', 'R', 'N', 'N', 'R', 'N', 'N', 'N', 'AF', 'N', 'N', 'AF', 'N', 'N', 'R', 'N', 'AF', 'R', 'N', 'N', 'R', 'R', 'AF', 'AF', 'R', 'AF', 'N', 'R', 'N', 'N', 'AF', 'AF', 'N', 'R', 'AF', 'N', 'AF', 'AF', 'R', 'AF', 'AF', 'AF', 'R', 'R', 'N', 'N', 'R', 'N', 'N', 'AF', 'N', 'AF', 'R', 'R', 'R', 'AF', 'AF', 'R', 'AF', 'AF', 'R', 'R', 'N', 'AF', 'R', 'AF', 'R', 'AF']

['N', 'R', 'R', 'N', 'N', 'AF', 'N', 'R', 'N', 'AF', 'N', 'N', 'N', 'R', 'AF', 'AF', 'N', 'AF', 'N', 'N', 'N', 'R', 'R', 'R', 'AF', 'R', 'N', 'N', 'R', 'R', 'R', 'N', 'N', 'AF', 'N', 'R', 'N', 'R', 'R', 'AF', 'AF', 'N', 'R', 'R', 'N', 'N', 'R', 'N', 'N', 'R', 'AF', 'AF', 'N', 'R', 'R', 'AF', 'AF', 'N', 'N', 'N', 'N', 'N', 'AF', 'R', 'R', 'N', 'R', 'R', 'N', 'AF', 'AF', 'N', 'R', 'AF', 'R', 'R', 'AF', 'AF', 'R', 'R', 'AF', 'R', 'R', 'AF', 'N', 'N', 'N', 'AF', 'AF', 'AF', 'AF', 'R', 'N', 'AF', 'AF', 'AF', 'AF', 'N', 'R', 'N', 'N', 'AF', 'R', 'AF', 'N', 'R', 'N', 'AF', 'AF', 'R', 'N', 'R', 'R', 'R', 'AF', 'AF', 'AF', 'N', 'R', 'R', 'N', 'N', 'AF', 'R', 'N', 'N', 'R', 'AF', 'R', 'R', 'N', 'R', 'N', 'N', 'R', 'N', 'N', 'N', 'AF', 'N', 'N', 'AF', 'N', 'N', 'R', 'N', 'AF', 'R', 'N', 'N', 'R', 'R', 'AF', 'AF', 'R', 'AF', 'N', 'R', 'N', 'N', 'AF', 'AF', 'N', 'R', 'AF', 'N', 'AF', 'AF', 'R', 'AF', 'AF', 'AF', 'R', 'R', 'N', 'N', 'R', 'N', 'N', 'AF', 'N', 'AF', 'R', 'R', 'R', 'AF', 'AF', 'R', 'AF', 'AF', 'R', 'R', 'N', 'AF', 'R', 'AF', 'R', 'AF']


In [99]:
theTotal = []
classDict = {}
lineCount = 0

x = open("REFERENCE-v3.csv")
for line in x:
    line = line.strip()
    a,b = line.split(",")
    theTotal.append(b)
    
    

  
#theFrame = {"mean":[],"std_dev":[],"theClass":[]}
theCsvX = pd.read_csv("Total_matrix_RR_interval_8528.csv",index_col=0)

theCsv = pd.read_csv("SD_matrix_8528_new_index.csv", index_col=0)
theCsv1 = pd.read_csv("Mean_matrix_8528.csv",index_col=0)
theCsv11 = pd.read_csv("Skew_matrix_8528.csv",index_col=0)
theCsv111 = pd.read_csv("Kurt_matrix_8528.csv",index_col=0)

theCsv2 = pd.read_csv("0_8528_Organized_Mean_sd_dimension_1.csv",index_col=0)
theCsv3 = pd.read_csv("0_8528_Organized_Mean_sd_dimension_2.csv",index_col=0)
theCsv4 = pd.read_csv("0-8528sum_of_lifetimes.csv",index_col=0)
#0-8528_sd_lifetimes.csv
theCsv5 = pd.read_csv("0_8528_skew_lifetimes_dim_1_2.csv",index_col=0)
theCsv6 = pd.read_csv("0_8528_Organized_Mean_sd_dimension_0.csv",index_col=0)
theCsv7 = pd.read_csv("0_8528_diagdist_mean_sd_dim12.csv",index_col=0)
#print(theCsv6["0"])
theCsv8 = pd.read_csv("0_8528_number_pts_dim_0_1_2.csv",index_col=0)
theCsv9 = pd.read_csv("0-8528_sd_lifetimes.csv",index_col=0)
'''
theCsv2 = pd.read_csv("Mean_sd_dimension_1.csv",index_col=0)
theCsv3 = pd.read_csv("Mean_sd_dimension_2.csv",index_col=0)

theCsv5 = pd.read_csv("Maximum_lifetimes_all_dims.csv",index_col=0)


theCsv9 = pd.read_csv("number_of_births_deaths_dim1.csv",index_col=0)
theCsv10 = pd.read_csv("number_of_births_deaths_dim2.csv",index_col=0)
theCsv11 = pd.read_csv("skewness_birth_dim012.csv",index_col=0)
theCsv12 = pd.read_csv("skewness_death_dim012.csv",index_col=0)
theCsv13 = pd.read_csv("a.csv",index_col=0)
theCsv14 = pd.read_csv("Total_matrix_RR_interval_2392.csv",index_col=0)
theCsv15 = pd.read_csv("rr_normal.csv",index_col=0)
theCsv16 = pd.read_csv("rr_R.csv",index_col=0)
'''
#theCsv8 = pd.read_csv("reduced_bottleneck_ave_sd_dist_dim2.csv",index_col=0)
#bigData = theCsv.append(theCsv2, ignore_index=True)

#print(bigData)

aList = []
aList2 = []
aList3 = []
for i in range(0,200):
    aList.append("N")
    aList2.append(0)
    aList3.append(0)

for i in range(0,200):
    aList.append("AF")
    aList2.append(1)
    aList3.append(0)
    
for i in range(0,200):
    aList.append("R")
    aList2.append(0)
    aList3.append(1)

#theCsv["Normal"] = np.asarray(aList)
#theCsv["AF"] = np.asarray(aList2)
#theCsv["Random"] = np.asarray(aList3)
#### make dataframe 
###

In [100]:
#theCsv

In [101]:
#theCsv2.loc[599] =[0,0,0,0]
#theCsv2.loc[600] =[0,0,0,0]
#theCsv2
#bigdata = pd.concat([theCsv, theCsv2])


#print(theCsv3["Means_dim2_birth"])

#theCsv["RR_AF_mean"] = theCsv14["0"]
#theCsv["RR_AF_SD"] = theCsv14["1"]
#theCsv["RR_AF_Skew"] = theCsv14["3"]

#theCsv["sd_life_dim1"] =theCsv5["sd_life_dim1"]
#theCsv["sd_life_dim2"] =theCsv5["sd_life_dim2"]
#theCsv["RR_top"] =theCsv6["0"]
theCsv["Mean_RR"] = theCsvX["0"]
theCsv["Skew_RR"] = theCsvX["1"]
theCsv["Kurt_RR"] = theCsvX["2"]
theCsv["Kurt_RR"] = theCsvX["3"]
theCsv["Means_dim1_birth"] = theCsv6["Means_dim0_birth"]
theCsv["Means_dim1_death"] = theCsv6["Means_dim0_birth"]
theCsv["sd_dim1_birth"] = theCsv6["sd_dim0_birth"]
theCsv["sd_dim1_death"] =theCsv6["sd_dim0_death"]

theCsv["Means_dim1_birth"] = theCsv2["Means_dim1_birth"]
theCsv["Means_dim1_death"] = theCsv2["Means_dim1_birth"]
theCsv["sd_dim1_birth"] = theCsv2["sd_dim1_birth"]
theCsv["sd_dim1_death"] =theCsv2["sd_dim1_death"]


#theCsv["Means_dim2_birth"] = theCsv3["Means_dim2_birth"]
theCsv["Means_dim2_death"] = theCsv3["Means_dim2_birth"]
theCsv["sd_dim2_birth"] = theCsv3["sd_dim2_birth"]
theCsv["sd_dim2_death"] =theCsv3["sd_dim2_death"]



#theCsv["Lifetime_dim0"] = theCsv4["Lifetime_dim0"]
theCsv["Lifetime_dim1"] = theCsv4["Lifetime_dim1"]
theCsv["Lifetime_dim2"] =theCsv4["Lifetime_dim2"]




#theCsv["V1"] =theCsv5["V2"]
#theCsv["sd_bottle_dist_dim0"] =theCsv5["Max_life_dim1"]

#theCsv["sd_life_dim1"] =theCsv5["sd_life_dim1"]
theCsv["skew_life_dim0"] =theCsv5["skew_life_dim0"]
theCsv["skew_life_dim1"] =theCsv5["skew_life_dim1"]
theCsv["skew_life_dim2"] =theCsv5["skew_life_dim2"]

#theCsv["avg_dist_dim2"] =theCsv7["avg_dist_dim2"]
theCsv["avg_dist_dim2"] =theCsv7["sd_dist_dim1"]

#theCsv["num_dim0"] = theCsv8["num_pts_dim0"]
theCsv["num_dim1"] = theCsv8["num_pts_dim1"]
#theCsv["num_dim2"] = theCsv8["num_pts_dim2"]


y = open("0-8528_sd_lifetimes.csv")

aList = []
aList2 =[]
count = 0
for line in y:
    if(count != 0):
        line = line.strip()
        a,b,c,d = line.split(",")
        aList.append(b)
        aList2.append(c)
    count +=  1
theCsv["sd_life_dim1"] = np.array(aList)
theCsv["sd_life_dim2"] = np.array(aList2)



#theCsv["RR_top"] 
#theCsv["RR_top"][8528] = 1000
#8528
'''
#theCsv["avg_bottle_dist_dim1"] =theCsv5["Max_life_dim0"]
#theCsv["sd_bottle_dist_dim1"] =theCsv6["V2"]

#
#theCsv["sd_bottle_dist_dim2"] =theCsv7["V2"]

#theCsv["num_dim0"] = theCsv8["x"]
#theCsv["num_dim1"] = theCsv9["x"]
#theCsv["num_dim2"] = theCsv10["x"]

#theCsv["num_dim1"] = theCsv10["x"]

#theCsv["skew_death1"] =theCsv12["skew.death.dim1"]
#theCsv["skew_death2"] =theCsv12["skew.death.dim2"]
#theCsv["skew_death0"] =theCsv12["skew.death.dim0"]


theCsv["skew_birth1"] = theCsv11["skew.birth.dim1"]
#theCsv["skew_birth2"] = theCsv11["skew.birth.dim2"]
print(len(theCsv["skew_birth1"]))

theCsv["num_per0"] = theCsv14["0"]
theCsv["num_per1"] = theCsv14["1"]
theCsv["num_per2"] = theCsv14["2"]
theCsv["num_per2"] = theCsv14["3"]



#theCsv["RR_R_mean"] = theCsv16["0"]
#print(theCsv)
#theCsv
#print(np.isnan(theCsv))

#theCsv["num_per0"][1956] = 1000
#theCsv["num_per1"][1956] = 1000
#theCsv["num_per2"][1956] = 1000
print(len(theTotal))
'''

print(theCsv)
theCsv["Normal"] = theTotal
theCsvX["Normal"] = theTotal
#theCsv
#print(theCsv)
#print(theTotal)
theCsv.fillna(1000)
theCsv.replace(np.inf, 1000)

#print(np.where(theCsv.values >= np.finfo(np.float64).max))
#theCsv
#theCsv = theCsv.loc[:, ~theCsv.columns.str.contains('^Unnamed')]


#theCsv22 = theCsv.isnull().any


#for i in range(0,8529):
#    if(theCsv22["RR_top"][i] != True):
#        print(i)








#print(theCsv["RR_top"])
#theCsv
theCsvX

               0     Mean_RR     Skew_RR   Kurt_RR  Means_dim1_birth  \
1       9.577564  228.500000    9.928030  0.141830          1.309917   
2      87.331613  248.428571   87.045238 -1.059212          0.714953   
3      27.370830  217.777778   27.424419 -3.700081          0.699906   
4      49.270636  282.741936   53.210457  0.536402          0.796660   
5      65.337020  162.700000   66.916169  1.178835          1.430684   
6      19.667469  310.642857   19.669073 -1.909149          0.477725   
7      15.158065  287.300000   15.539520 -0.404926          0.669206   
8      47.195133  258.246377   47.675353 -1.794191          0.904354   
9      31.578818  189.282609   33.261587  0.504180          1.202949   
10      6.863423  276.015625    7.003330 -0.200431          0.561889   
11      4.524061  254.285714    4.651092 -0.786530          0.795387   
12     10.817183  267.593750   10.708815 -2.474211          0.391169   
13      6.200673  193.133333   10.910953  3.242943          1.45

0           1          2         3 Normal
1     228.500000    9.928030  -1.141563  0.141830      N
2     248.428571   87.045238  -0.637351 -1.059212      N
3     217.777778   27.424419  15.664116 -3.700081      N
4     282.741936   53.210457  -0.882869  0.536402      A
5     162.700000   66.916169   0.018919  1.178835      A
6     310.642857   19.669073   3.052003 -1.909149      N
7     287.300000   15.539520  -0.813542 -0.404926      N
8     258.246377   47.675353   3.038294 -1.794191      O
9     189.282609   33.261587  -0.336344  0.504180      A
10    276.015625    7.003330  -0.729946 -0.200431      N
11    254.285714    4.651092   0.901482 -0.786530      N
12    267.593750   10.708815   4.614951 -2.474211      N
13    193.133333   10.910953  18.199330  3.242943      O
14    324.812500   25.671528  -1.214587 -0.114771      N
15    196.766667   63.109790  -0.902205  0.113302      A
16    214.585366   26.475922  21.186206 -4.415577      N
17    120.589041    4.040330  -0.435261 -0.262060      O
18    335.720000   10.113437  -0.285762 -0.626692      N
19    238.404255   27.970090   7.961796 -2.471607      N
20    226.894737   22.762838   9.349495  0.180133      O
21    281.967742    5.778067  -1.334351 -0.195120      N
22    222.850000  169.642352   8.702050  2.911617      ~
23    247.028571   29.749896   8.563344 -2.965295      O
24    246.314286   53.663913   3.443522 -2.165616      O
25    295.655172    4.907952  -1.194999 -0.220557      N
26    309.750000    2.640684  -0.858609 -0.217468      N
27    196.931818   37.330464  -0.297930  0.673173      A
28    281.984127    2.319634  -0.149694  0.248172      N
29    176.755102    5.698301   1.021789  1.125003      O
30    284.403226  101.345538  -1.568802 -0.274236      O
...          ...         ...        ...       ...    ...
8499  181.958333   22.644865   1.645370 -1.513185      O
8500  148.576271   18.095981  -1.358675  0.281033      A
8501  282.825397   52.716233  10.897689  2.742330      O
8502  276.580645   10.425695  -0.400474 -0.102523      N
8503  221.564103    5.157990  -0.356972  0.421362      N
8504  226.025641   10.721383   5.615686 -1.729369      O
8505  237.918919   46.829985   6.728163 -2.851293      N
8506  291.533333   42.731513  23.337925 -4.943215      N
8507  274.218750    6.989878   0.617119 -0.765557      N
8508  259.181818   12.551601  -0.473647 -0.308177      N
8509  253.735294   41.100529  13.111226 -3.788680      N
8510  173.568627    1.033837   0.270616 -0.769491      O
8511  230.447368    8.397046  15.035244  2.441956      O
8512  290.400000   28.367352   0.134531 -0.101882      N
8513  206.627119   27.373065   9.970939 -3.325815      N
8514  199.187500   42.237748   2.109998  1.510208      A
8515  216.200000   16.816956  -0.665362 -0.327816      N
8516  381.739130   66.485839  11.633494 -3.338505      O
8517  250.485714    7.936791  -0.587300 -0.311433      N
8518  293.965517   32.337107  -1.341169 -0.215131      N
8519  233.783784    8.989890  -1.113530 -0.302877      O
8520  302.241379   32.310621  15.176696 -0.259586      O
8521  410.047619  214.533486  13.000457  3.669157      A
8522  248.857143    3.339314  -0.512396  0.138394      N
8523  261.515152   63.327968   1.536900  0.932250      A
8524  259.575758    8.127881  -1.000161  0.158649      N
8525  205.142857   32.600447   1.487935 -1.228331      O
8526  246.744186   20.061641  -0.751354 -0.206552      N
8527  177.620000   20.273026  11.742134 -3.238385      N
8528  282.933333    9.979757  -0.363450 -0.367776      N

[8528 rows x 5 columns]

In [102]:
### code from meduim torwards data scienec example
# Labels are the values we want to pred

labels = np.array(theCsvX["Normal"])

# Remove the labels from the features
# axis 1 refers to the columns
theCsvX = theCsvX.drop('Normal', axis = 1)
#theCsv = theCsv.drop('AF', axis = 1)
#theCsv = theCsv.drop('Random', axis = 1)

# Saving feature names for later use
feature_list = list(theCsvX.columns)

# Convert to numpy array
features = np.array(theCsvX)


# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split


# Split the data into training and testing sets
train_features, test_features, train_labels, test_labels = train_test_split(theCsvX, labels, test_size = 0.11726, random_state = 42)


print(test_labels.tolist())

['N', 'N', 'N', 'O', 'O', 'N', 'O', 'N', 'N', 'N', 'N', 'N', 'N', 'O', 'N', '~', 'N', 'N', 'O', 'O', 'N', 'O', 'N', 'O', 'A', 'O', '~', 'N', 'N', 'O', 'N', 'O', 'N', 'N', 'O', 'O', 'N', 'N', 'N', 'N', 'N', 'N', 'O', 'N', 'O', 'A', 'N', 'N', 'N', 'A', 'N', 'O', 'N', 'N', 'A', 'N', 'N', 'N', 'N', 'O', 'N', 'O', 'N', 'O', 'A', 'O', 'O', 'N', 'N', 'N', 'N', 'O', 'N', 'N', 'N', 'N', 'N', '~', 'O', 'A', 'N', 'N', 'O', 'A', 'O', 'N', 'N', 'O', 'N', 'A', 'N', 'O', 'A', 'N', 'N', 'N', 'O', 'N', 'O', 'O', 'N', 'N', 'N', 'N', 'O', 'N', '~', 'A', 'N', 'N', 'N', 'N', '~', 'N', 'N', 'N', 'O', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'A', 'N', 'N', 'N', 'N', 'O', 'O', 'N', 'N', 'N', 'N', 'N', 'N', 'O', 'N', 'O', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'O', 'N', 'N', 'N', 'N', 'O', 'N', 'O', 'N', 'A', 'N', 'N', 'A', 'N', 'O', 'A', 'O', 'N', 'N', 'O', 'N', 'A', 'N', 'N', 'N', 'O', 'N', 'O', 'N', 'N', 'N', 'N', 'N', 'N', 'O', 'O', 'A', 'O', 'A', 'O', 'O', 'A', 'O', 'O', 'N', 'O', 'N', 'N', 'N', 'N', 'N',

In [103]:
# Import the model we are using
#from sklearn.ensemble import RandomForest
predict_list = []
# Instantiate model with 1000 decision trees
for i in range(0,1):
    #rf = RandomForestClassifier(bootstrap=True,max_depth=20,max_features="sqrt",min_samples_leaf=4,min_samples_split=10,n_estimators=50,random_state=118)
    rf = RandomForestClassifier(bootstrap=True,max_depth=10,max_features="sqrt",min_samples_leaf=1,min_samples_split=5,n_estimators=600,random_state=40)

#rf = RandomForestClassifier(bootstrap=True,max_depth=10,max_features="sqrt",min_samples_leaf=1,min_samples_split=5,n_estimators=600,random_state=42)

    

# Train the model on training data
    rf.fit(train_features, train_labels)

    predictions = rf.predict(test_features)
    predict_list.append(predictions)

In [104]:
print(predictions)

['N' 'N' 'N' 'O' 'O' 'N' 'O' 'N' 'N' 'N' 'N' 'N' 'N' 'O' 'N' '~' 'N' 'N'
 'N' 'O' 'N' 'N' 'N' 'O' 'A' 'O' '~' 'N' 'N' 'N' 'N' 'O' 'N' 'N' 'O' 'N'
 'N' 'N' 'O' 'N' 'N' 'N' 'O' 'N' 'O' 'N' 'N' 'N' 'N' 'A' 'N' 'O' 'N' 'N'
 'A' 'N' 'N' 'N' 'N' 'O' 'N' 'O' 'N' 'O' 'A' 'O' 'O' 'N' 'N' 'N' 'N' 'N'
 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'A' 'N' 'O' 'N' 'A' 'N' 'N' 'N' 'O' 'N' 'A'
 'N' 'O' 'A' 'A' 'N' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'N' 'N' 'O' 'N' 'N' 'N'
 'N' 'N' 'O' 'N' 'O' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'A' 'N'
 'N' 'N' 'N' 'N' 'O' 'N' 'N' 'A' 'O' 'N' 'N' 'O' 'N' 'O' 'N' 'N' 'O' 'N'
 'N' 'O' 'N' 'N' 'N' 'O' 'N' 'O' 'N' 'N' 'O' 'N' 'O' 'N' 'A' 'N' 'N' 'A'
 'N' 'O' 'A' 'O' 'N' 'N' 'O' 'N' 'A' 'N' 'O' 'N' 'N' 'N' 'O' 'N' 'N' 'N'
 'N' 'N' 'O' 'N' 'N' 'O' 'O' 'O' 'A' 'N' 'A' 'N' 'O' 'N' 'O' 'N' 'N' 'N'
 'N' 'N' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'O' 'N' 'O' 'N'
 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'O' 'N' 'N' 'O' 'N'
 'N' 'O' 'N' 'O' 'N' 'A' 'N' 'A' 'N' 'N' 'N' 'N' 'N

In [105]:
print(test_labels)

['N' 'N' 'N' 'O' 'O' 'N' 'O' 'N' 'N' 'N' 'N' 'N' 'N' 'O' 'N' '~' 'N' 'N'
 'O' 'O' 'N' 'O' 'N' 'O' 'A' 'O' '~' 'N' 'N' 'O' 'N' 'O' 'N' 'N' 'O' 'O'
 'N' 'N' 'N' 'N' 'N' 'N' 'O' 'N' 'O' 'A' 'N' 'N' 'N' 'A' 'N' 'O' 'N' 'N'
 'A' 'N' 'N' 'N' 'N' 'O' 'N' 'O' 'N' 'O' 'A' 'O' 'O' 'N' 'N' 'N' 'N' 'O'
 'N' 'N' 'N' 'N' 'N' '~' 'O' 'A' 'N' 'N' 'O' 'A' 'O' 'N' 'N' 'O' 'N' 'A'
 'N' 'O' 'A' 'N' 'N' 'N' 'O' 'N' 'O' 'O' 'N' 'N' 'N' 'N' 'O' 'N' '~' 'A'
 'N' 'N' 'N' 'N' '~' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'A' 'N'
 'N' 'N' 'N' 'O' 'O' 'N' 'N' 'N' 'N' 'N' 'N' 'O' 'N' 'O' 'N' 'N' 'N' 'N'
 'N' 'N' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'N' 'O' 'N' 'O' 'N' 'A' 'N' 'N' 'A'
 'N' 'O' 'A' 'O' 'N' 'N' 'O' 'N' 'A' 'N' 'N' 'N' 'O' 'N' 'O' 'N' 'N' 'N'
 'N' 'N' 'N' 'O' 'O' 'A' 'O' 'A' 'O' 'O' 'A' 'O' 'O' 'N' 'O' 'N' 'N' 'N'
 'N' 'N' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'O' 'N' 'A' 'O'
 'N' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'O' 'O' 'O' 'N' 'A' 'N'
 'O' 'A' 'N' 'O' 'O' 'A' 'N' 'A' 'N' 'N' 'N' 'N' 'N

In [106]:
theMax = 0
for i in range(0,1):    
    if(accuracy_score(test_labels, predict_list[i]) > theMax):
        theMax = np.average(f1_score(test_labels, predictions, average=None))
print(theMax)

0.649941219998


In [107]:
results = confusion_matrix(test_labels, predictions,labels=["A", "N", "O","~"])
print(results)

[[ 52  13  24   0]
 [  5 552  42   4]
 [ 14 103 152   6]
 [  3   9   7  14]]


In [108]:
#print('Parameters currently in use:\n')
#print(rf.get_params())

In [109]:



var1 = 36/(29+28)
var2 = 48/(31+39)
var3 = 112/(73+66)

print((var1+var2+var3)/3)

0.7076828762553866
