In [53]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score

theCsv["avg_bottle_dist_dim0"] =theCsv5["avg_bottle_dist_dim0"]
theCsv["sd_bottle_dist_dim0"] =theCsv5["sd_bottle_dist_dim0"]


#theCsv["avg_bottle_dist_dim0"] =theCsv6["avg_bottle_dist_dim0"]
#theCsv["sd_bottle_dist_dim0"] =theCsv6["sd_bottle_dist_dim0"]

theCsv["avg_bottle_dist_dim0"] =theCsv7["avg_bottle_dist_dim0"]
theCsv["sd_bottle_dist_dim0"] =theCsv7["sd_bottle_dist_dim0"]
118

['N', 'R', 'R', 'N', 'N', 'AF', 'N', 'R', 'N', 'AF', 'N', 'N', 'N', 'R', 'AF', 'AF', 'N', 'AF', 'N', 'N', 'N', 'R', 'R', 'R', 'AF', 'R', 'N', 'N', 'R', 'R', 'R', 'N', 'N', 'AF', 'N', 'R', 'N', 'R', 'R', 'AF', 'AF', 'N', 'R', 'R', 'N', 'N', 'R', 'N', 'N', 'R', 'AF', 'AF', 'N', 'R', 'R', 'AF', 'AF', 'N', 'N', 'N', 'N', 'N', 'AF', 'R', 'R', 'N', 'R', 'R', 'N', 'AF', 'AF', 'N', 'R', 'AF', 'R', 'R', 'AF', 'AF', 'R', 'R', 'AF', 'R', 'R', 'AF', 'N', 'N', 'N', 'AF', 'AF', 'AF', 'AF', 'R', 'N', 'AF', 'AF', 'AF', 'AF', 'N', 'R', 'N', 'N', 'AF', 'R', 'AF', 'N', 'R', 'N', 'AF', 'AF', 'R', 'N', 'R', 'R', 'R', 'AF', 'AF', 'AF', 'N', 'R', 'R', 'N', 'N', 'AF', 'R', 'N', 'N', 'R', 'AF', 'R', 'R', 'N', 'R', 'N', 'N', 'R', 'N', 'N', 'N', 'AF', 'N', 'N', 'AF', 'N', 'N', 'R', 'N', 'AF', 'R', 'N', 'N', 'R', 'R', 'AF', 'AF', 'R', 'AF', 'N', 'R', 'N', 'N', 'AF', 'AF', 'N', 'R', 'AF', 'N', 'AF', 'AF', 'R', 'AF', 'AF', 'AF', 'R', 'R', 'N', 'N', 'R', 'N', 'N', 'AF', 'N', 'AF', 'R', 'R', 'R', 'AF', 'AF', 'R', 'AF', 'AF', 'R', 'R', 'N', 'AF', 'R', 'AF', 'R', 'AF']

['N', 'R', 'R', 'N', 'N', 'AF', 'N', 'R', 'N', 'AF', 'N', 'N', 'N', 'R', 'AF', 'AF', 'N', 'AF', 'N', 'N', 'N', 'R', 'R', 'R', 'AF', 'R', 'N', 'N', 'R', 'R', 'R', 'N', 'N', 'AF', 'N', 'R', 'N', 'R', 'R', 'AF', 'AF', 'N', 'R', 'R', 'N', 'N', 'R', 'N', 'N', 'R', 'AF', 'AF', 'N', 'R', 'R', 'AF', 'AF', 'N', 'N', 'N', 'N', 'N', 'AF', 'R', 'R', 'N', 'R', 'R', 'N', 'AF', 'AF', 'N', 'R', 'AF', 'R', 'R', 'AF', 'AF', 'R', 'R', 'AF', 'R', 'R', 'AF', 'N', 'N', 'N', 'AF', 'AF', 'AF', 'AF', 'R', 'N', 'AF', 'AF', 'AF', 'AF', 'N', 'R', 'N', 'N', 'AF', 'R', 'AF', 'N', 'R', 'N', 'AF', 'AF', 'R', 'N', 'R', 'R', 'R', 'AF', 'AF', 'AF', 'N', 'R', 'R', 'N', 'N', 'AF', 'R', 'N', 'N', 'R', 'AF', 'R', 'R', 'N', 'R', 'N', 'N', 'R', 'N', 'N', 'N', 'AF', 'N', 'N', 'AF', 'N', 'N', 'R', 'N', 'AF', 'R', 'N', 'N', 'R', 'R', 'AF', 'AF', 'R', 'AF', 'N', 'R', 'N', 'N', 'AF', 'AF', 'N', 'R', 'AF', 'N', 'AF', 'AF', 'R', 'AF', 'AF', 'AF', 'R', 'R', 'N', 'N', 'R', 'N', 'N', 'AF', 'N', 'AF', 'R', 'R', 'R', 'AF', 'AF', 'R', 'AF', 'AF', 'R', 'R', 'N', 'AF', 'R', 'AF', 'R', 'AF']


In [54]:
theTotal = []
classDict = {}
lineCount = 0

x = open("labels_aa.csv")
for line in x:
    line = line.strip()
    if(line != ""):
        print(line)
        a,b = line.split(",")
        print(a[len(a)-1])
        theTotal.append(b)
    
    lineCount += 1
#theTotal = theTotal[1:len(theTotal)]
#labs = 
            
theFrame = {"mean":[],"std_dev":[],"theClass":[]}

theCsv = pd.read_csv("Mean_sd_dimension_0.csv", index_col=0)
theCsv2 = pd.read_csv("Mean_sd_dimension_1.csv",index_col=0)
theCsv3 = pd.read_csv("Mean_sd_dimension_2.csv",index_col=0)
theCsv4 = pd.read_csv("Lifetimes_dim_0_1_2(1).csv",index_col=0)
theCsv5 = pd.read_csv("Maximum_lifetimes_all_dims.csv",index_col=0)
theCsv6 = pd.read_csv("reduced_bottleneck_ave_sd_dist_dim1.csv",index_col=0)
theCsv7 = pd.read_csv("reduced_bottleneck_ave_sd_dist_dim2.csv",index_col=0)
theCsv8 = pd.read_csv("number_of_births_deaths_dim0.csv",index_col=0)
theCsv9 = pd.read_csv("number_of_births_deaths_dim1.csv",index_col=0)
theCsv10 = pd.read_csv("number_of_births_deaths_dim2.csv",index_col=0)
theCsv11 = pd.read_csv("skewness_birth_dim012.csv",index_col=0)
theCsv12 = pd.read_csv("skewness_death_dim012.csv",index_col=0)
theCsv13 = pd.read_csv("kurtosis_birth_dim012.csv",index_col=0)
theCsv14 = pd.read_csv("Total_matrix_RR_interval_2392(1).csv",index_col=0)
theCsv15 = pd.read_csv("matrix_stats_coutA02392.csv",index_col=0)
theCsv16 = pd.read_csv("rr_R.csv",index_col=0)

theCsv17 = pd.read_csv("kurtosis_death_dim012.csv",index_col=0)
#theCsv8 = pd.read_csv("reduced_bottleneck_ave_sd_dist_dim2.csv",index_col=0)
#bigData = theCsv.append(theCsv2, ignore_index=True)

#print(bigData)

aList = []
aList2 = []
aList3 = []
for i in range(0,200):
    aList.append("N")
    aList2.append(0)
    aList3.append(0)

for i in range(0,200):
    aList.append("AF")
    aList2.append(1)
    aList3.append(0)
    
for i in range(0,200):
    aList.append("R")
    aList2.append(0)
    aList3.append(1)

#theCsv["Normal"] = np.asarray(aList)
#theCsv["AF"] = np.asarray(aList2)
#theCsv["Random"] = np.asarray(aList3)
#### make dataframe 
###
#bigData  

A00001,N
1
A00002,N
2
A00003,N
3
A00006,N
6
A00007,N
7
A00010,N
0
A00011,N
1
A00012,N
2
A00014,N
4
A00016,N
6
A00018,N
8
A00019,N
9
A00021,N
1
A00025,N
5
A00026,N
6
A00028,N
8
A00031,N
1
A00032,N
2
A00033,N
3
A00035,N
5
A00036,N
6
A00037,N
7
A00039,N
9
A00040,N
0
A00042,N
2
A00044,N
4
A00045,N
5
A00046,N
6
A00048,N
8
A00049,N
9
A00050,N
0
A00051,N
1
A00052,N
2
A00053,N
3
A00057,N
7
A00059,N
9
A00060,N
0
A00062,N
2
A00063,N
3
A00064,N
4
A00066,N
6
A00068,N
8
A00072,N
2
A00073,N
3
A00076,N
6
A00079,N
9
A00080,N
0
A00081,N
1
A00084,N
4
A00085,N
5
A00086,N
6
A00089,N
9
A00091,N
1
A00093,N
3
A00094,N
4
A00095,N
5
A00097,N
7
A00098,N
8
A00099,N
9
A00104,N
4
A00105,N
5
A00109,N
9
A00111,N
1
A00112,N
2
A00113,N
3
A00116,N
6
A00117,N
7
A00118,N
8
A00122,N
2
A00124,N
4
A00127,N
7
A00129,N
9
A00130,N
0
A00134,N
4
A00135,N
5
A00140,N
0
A00142,N
2
A00143,N
3
A00144,N
4
A00146,N
6
A00147,N
7
A00148,N
8
A00149,N
9
A00150,N
0
A00151,N
1
A00152,N
2
A00153,N
3
A00154,N
4
A00157,N
7
A00160,N
0
A00163,N
3

A01874,N
4
A01875,N
5
A01877,N
7
A01878,N
8
A01879,N
9
A01881,N
1
A01882,N
2
A01884,N
4
A01885,N
5
A01886,N
6
A01887,N
7
A01889,N
9
A01894,N
4
A01895,N
5
A01896,N
6
A01898,N
8
A01899,N
9
A01900,N
0
A01901,N
1
A01904,N
4
A01905,N
5
A01906,N
6
A01908,N
8
A01910,N
0
A01911,N
1
A01912,N
2
A01914,N
4
A01915,N
5
A01920,N
0
A01922,N
2
A01923,N
3
A01924,N
4
A01926,N
6
A01927,N
7
A01931,N
1
A01933,N
3
A01934,N
4
A01935,N
5
A01936,N
6
A01939,N
9
A01940,N
0
A01942,N
2
A01943,N
3
A01945,N
5
A01947,N
7
A01948,N
8
A01949,N
9
A01950,N
0
A01952,N
2
A01953,N
3
A01956,N
6
A01957,N
7
A01958,N
8
A01959,N
9
A01960,N
0
A01963,N
3
A01964,N
4
A01967,N
7
A01968,N
8
A01969,N
9
A01971,N
1
A01972,N
2
A01973,N
3
A01975,N
5
A01976,N
6
A01977,N
7
A01978,N
8
A01979,N
9
A01980,N
0
A01982,N
2
A01984,N
4
A01985,N
5
A01987,N
7
A01988,N
8
A01989,N
9
A01990,N
0
A01992,N
2
A01993,N
3
A01994,N
4
A01995,N
5
A01996,N
6
A01998,N
8
A02000,N
0
A02001,N
1
A02006,N
6
A02008,N
8
A02009,N
9
A02010,N
0
A02013,N
3
A02015,N
5
A02016,N
6

A01746,O
6
A01757,O
7
A01761,O
1
A01764,O
4
A01774,O
4
A01777,O
7
A01785,O
5
A01790,O
0
A01795,O
5
A01798,O
8
A01801,O
1
A01809,O
9
A01813,O
3
A01814,O
4
A01820,O
0
A01822,O
2
A01825,O
5
A01826,O
6
A01829,O
9
A01834,O
4
A01836,O
6
A01839,O
9
A01842,O
2
A01846,O
6
A01852,O
2
A01860,O
0
A01872,O
2
A01873,O
3
A01876,O
6
A01880,O
0
A01890,O
0
A01891,O
1
A01893,O
3
A01897,O
7
A01902,O
2
A01903,O
3
A01907,O
7
A01909,O
9
A01913,O
3
A01916,O
6
A01918,O
8
A01919,O
9
A01921,O
1
A01925,O
5
A01928,O
8
A01929,O
9
A01937,O
7
A01944,O
4
A01946,O
6
A01954,O
4
A01955,O
5
A01961,O
1
A01962,O
2
A01970,O
0
A01974,O
4
A01983,O
3
A01997,O
7
A01999,O
9
A02002,O
2
A02003,O
3
A02004,O
4
A02005,O
5
A02007,O
7
A02011,O
1
A02012,O
2
A02014,O
4
A02019,O
9
A02024,O
4
A02027,O
7
A02031,O
1
A02035,O
5
A02036,O
6
A02044,O
4
A02049,O
9
A02053,O
3
A02056,O
6
A02060,O
0
A02062,O
2
A02066,O
6
A02067,O
7
A02068,O
8
A02077,O
7
A02084,O
4
A02090,O
0
A02091,O
1
A02092,O
2
A02101,O
1
A02103,O
3
A02105,O
5
A02107,O
7
A02111,O
1

In [55]:
#theCsv

In [56]:
#theCsv2.loc[599] =[0,0,0,0]
#theCsv2.loc[600] =[0,0,0,0]
#theCsv2
#bigdata = pd.concat([theCsv, theCsv2])


#theCsv["RR_AF_mean"] = theCsv14["0"]
#theCsv["RR_AF_SD"] = theCsv14["1"]
#theCsv["RR_AF_Skew"] = theCsv14["3"]

theCsv["Means_dim1_birth"] = theCsv2["Means_dim1_birth"]
theCsv["Means_dim1_death"] = theCsv2["Means_dim1_birth"]
theCsv["sd_dim1_birth"] = theCsv2["sd_dim1_birth"]
theCsv["sd_dim1_death"] =theCsv2["sd_dim1_death"]

theCsv["Means_dim2_birth"] = theCsv3["Means_dim2_birth"]
theCsv["Means_dim2_death"] = theCsv3["Means_dim2_birth"]
theCsv["sd_dim2_birth"] = theCsv3["sd_dim2_birth"]
theCsv["sd_dim2_death"] =theCsv3["sd_dim2_death"]



#theCsv["RR_AF_mean"] = theCsv14["0"]
#theCsv["RR_AF_SD"] = theCsv14["1"]
#theCsv["RR_AF_Skew"] = theCsv14["3"]

#theCsv["Means_dim0_birth"] = theCsv4["Means_dim0_birth"]
#theCsv["Means_dim0_death"] = theCsv4["Means_dim0_birth"]
#theCsv["sd_dim0_birth"] = theCsv4["sd_dim0_birth"]
#theCsv["sd_dim0_death"] =theCsv4["sd_dim0_death"]


theCsv["Lifetime_dim0"] = theCsv4["Lifetime_dim0"]
theCsv["Lifetime_dim1"] = theCsv4["Lifetime_dim1"]
theCsv["Lifetime_dim2"] =theCsv4["Lifetime_dim2"]

#skewness_birth_dim012.csv


#theCsv["avg_bottle_dist_dim0"] =theCsv5["Max_life_dim0"]
#theCsv["sd_bottle_dist_dim0"] =theCsv5["Max_life_dim1"]


#theCsv["avg_bottle_dist_dim1"] =theCsv5["Max_life_dim0"]
#theCsv["sd_bottle_dist_dim1"] =theCsv6["V2"]

#theCsv["avg_bottle_dist_dim2"] =theCsv7["V1"]
#theCsv["sd_bottle_dist_dim2"] =theCsv7["V2"]

#theCsv["num_dim0"] = theCsv8["x"]
#theCsv["num_dim1"] = theCsv9["x"]
#theCsv["num_dim2"] = theCsv10["x"]

#theCsv["num_dim1"] = theCsv10["x"]
'''
theCsv["skew_death1"] =theCsv12["skew.death.dim1"]
theCsv["skew_death2"] =theCsv12["skew.death.dim2"]
theCsv["skew_death0"] =theCsv12["skew.death.dim0"]


theCsv["kurt.birth.dim1"] = theCsv13["kurt.birth.dim1"]
#theCsv["skew_birth2"] = theCsv11["skew.birth.dim2"]
'''

theCsv["kurt.birth.dim1"] = theCsv13["kurt.birth.dim1"]
#theCsv["kurt.birth.dim2"] = theCsv13["kurt.birth.dim2"]

theCsv["kurt.death.dim2"] = theCsv17["kurt.death.dim0.1"]

theCsv["num_per0"] = theCsv14["0"]
theCsv["num_per1"] = theCsv14["1"]
theCsv["num_per2"] = theCsv14["2"]
theCsv["num_per3"] = theCsv14["3"]



theCsv["RR_R_mean"] = theCsv15["V3"]


#theCsv["RR_R_mean"] = theCsv16["0"]
#print(theCsv)
#theCsv
#print(np.isnan(theCsv))

theCsv["num_per0"][2392] = 1000
theCsv["num_per1"][2392] = 1000
theCsv["num_per2"][2392] = 1000
theCsv["num_per3"][2392] = 1000

print(len(theTotal))
print(len(theCsv14["3"]))
print(theCsv)
theCsv["Normal"] = theTotal
#[0:len(theTotal)-12]
theCsv14["Normal"] = theTotal
#theCsv
print(theCsv)


print(theTotal)
#theCsv.fillna(theCsv.mean())

#print(np.where(theCsv.values >= np.finfo(np.float64).max))

/home/dr-dunstan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:85: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/dr-dunstan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:86: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/dr-dunstan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:87: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/dr-dunstan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:88: SettingWithCopyWarning: 
A value i

2392
2392
      Means_dim0_birth  Means_dim0_death  sd_dim0_birth  sd_dim0_death  \
1                    0          0.532601              0       0.282795   
2                    0          0.503053              0       0.268632   
3                    0          0.379515              0       0.143459   
4                    0          0.272712              0       0.128959   
5                    0          0.266372              0       0.131238   
6                    0          0.394447              0       0.103590   
7                    0          0.513328              0       0.092833   
8                    0          0.213943              0       0.053455   
9                    0          0.778684              0       0.267724   
10                   0          0.740375              0       0.296588   
11                   0          0.219961              0       0.065375   
12                   0          0.428692              0       0.312847   
13                   0      

      Means_dim0_birth  Means_dim0_death  sd_dim0_birth  sd_dim0_death  \
1                    0          0.532601              0       0.282795   
2                    0          0.503053              0       0.268632   
3                    0          0.379515              0       0.143459   
4                    0          0.272712              0       0.128959   
5                    0          0.266372              0       0.131238   
6                    0          0.394447              0       0.103590   
7                    0          0.513328              0       0.092833   
8                    0          0.213943              0       0.053455   
9                    0          0.778684              0       0.267724   
10                   0          0.740375              0       0.296588   
11                   0          0.219961              0       0.065375   
12                   0          0.428692              0       0.312847   
13                   0          0.2840

In [57]:
### code from meduim torwards data scienec example
# Labels are the values we want to pred

labels = np.array(theCsv["Normal"])

# Remove the labels from the features
# axis 1 refers to the columns
theCsv = theCsv.drop('Normal', axis = 1)
#theCsv = theCsv.drop('AF', axis = 1)
#theCsv = theCsv.drop('Random', axis = 1)

# Saving feature names for later use
feature_list = list(theCsv.columns)

# Convert to numpy array
features = np.array(theCsv)


# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split



# Split the data into training and testing sets
train_features, test_features, train_labels, test_labels = train_test_split(theCsv, labels, test_size = 0.33, random_state = 42)


print(train_features)

      Means_dim0_birth  Means_dim0_death  sd_dim0_birth  sd_dim0_death  \
1548                 0          0.459613              0       0.259388   
2121                 0          0.582011              0       0.184104   
1273                 0          0.260998              0       0.117244   
1961                 0          0.266547              0       0.114204   
1081                 0          0.514701              0       0.210914   
345                  0          0.530751              0       0.094611   
557                  0          0.658635              0       0.132976   
1284                 0          0.384460              0       0.139245   
1592                 0          1.245368              0       0.198701   
681                  0          0.441699              0       0.253882   
1989                 0          0.466058              0       0.163719   
1436                 0          1.055505              0       0.245073   
353                  0          0.5440

In [58]:
# Import the model we are using
#from sklearn.ensemble import RandomForest
predict_list = []
# Instantiate model with 1000 decision trees
for i in range(0,100):
    rf = RandomForestClassifier(bootstrap=True,max_depth=20,max_features="sqrt",min_samples_leaf=4,min_samples_split=10,n_estimators=50,random_state=i,class_weight="balanced")
   # rf = RandomForestClassifier(random_state=i,class_weight="balanced")

#rf = RandomForestClassifier(bootstrap=True,max_depth=10,max_features="sqrt",min_samples_leaf=1,min_samples_split=5,n_estimators=600,random_state=42)

    

# Train the model on training data
    rf.fit(train_features, train_labels)

    predictions = rf.predict(test_features)
    predict_list.append(predictions)

In [59]:
print(predictions)

['N' 'N' 'N' 'A' 'N' 'N' 'O' 'A' 'N' 'N' 'O' 'N' 'N' 'N' 'O' 'N' 'O' 'N'
 'N' 'N' 'A' 'N' 'N' 'A' 'N' 'N' 'N' 'A' 'N' 'N' 'N' 'N' 'N' 'N' 'O' 'O'
 'O' 'N' 'N' 'O' 'A' 'N' 'N' 'O' 'N' 'N' 'A' 'N' 'N' 'N' 'N' 'N' 'A' 'N'
 'N' 'N' 'N' 'A' 'N' 'N' 'A' 'N' 'O' 'N' 'O' 'O' 'A' 'N' 'N' 'N' 'O' 'N'
 'N' 'N' 'N' 'O' 'N' 'A' 'O' 'N' 'A' 'O' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'N'
 'N' 'N' 'N' 'O' 'A' 'N' 'N' 'N' 'O' 'N' 'N' 'A' 'N' 'O' 'N' 'N' 'N' 'A'
 'N' 'N' 'O' 'A' 'O' 'O' 'A' 'N' 'N' 'O' 'O' 'N' 'A' 'O' 'N' 'O' 'O' 'N'
 'N' 'N' 'N' 'N' 'N' 'O' 'N' 'O' 'N' 'N' 'O' 'N' 'N' 'N' 'N' 'N' 'O' 'O'
 'O' 'N' 'N' 'O' 'O' 'N' 'O' 'N' 'O' 'O' 'O' '~' 'N' 'N' 'N' 'O' 'A' 'N'
 'N' 'N' 'N' 'N' 'O' 'N' '~' 'N' 'N' 'N' 'N' 'N' 'N' 'O' 'O' 'N' 'O' 'N'
 'N' 'N' 'A' 'N' 'O' 'N' 'A' 'N' 'O' 'N' 'N' 'A' 'N' 'N' 'N' '~' 'N' 'O'
 'N' 'N' 'N' 'O' 'O' 'O' 'N' 'N' 'N' 'N' 'A' 'N' 'A' 'N' 'N' 'N' 'A' 'N'
 'O' 'N' 'N' 'O' 'N' 'N' 'O' 'O' 'N' 'N' 'O' 'N' 'A' 'O' 'N' 'N' 'N' 'N'
 'A' 'A' '~' 'O' 'N' 'N' 'N' 'N' 'N' '~' 'N' 'O' 'N

In [60]:
print(test_labels)

['N' 'N' 'O' '~' 'N' 'N' 'A' '~' 'N' 'N' 'O' 'N' 'N' 'O' 'N' 'N' 'O' 'N'
 'O' 'N' 'O' 'A' 'O' 'N' 'O' 'N' 'N' 'A' 'N' 'N' 'N' 'N' 'N' 'N' 'O' '~'
 'N' 'O' 'N' 'O' 'O' 'N' 'N' 'N' 'N' 'N' '~' 'N' 'O' 'N' 'N' 'N' 'A' 'N'
 'O' 'N' 'O' 'O' 'N' 'O' 'O' 'N' 'O' 'N' 'A' 'O' 'O' 'N' 'O' 'N' 'N' 'O'
 'O' 'N' 'N' 'A' 'N' 'O' 'N' 'N' 'A' 'O' 'N' 'N' 'N' 'N' 'N' 'N' 'O' 'N'
 'N' 'N' 'N' 'O' 'O' 'N' 'N' 'N' 'A' 'N' 'N' 'O' 'N' 'O' 'O' 'N' 'N' 'A'
 'N' 'O' 'O' 'A' 'O' '~' 'A' 'O' 'O' 'O' 'N' 'N' 'A' '~' 'N' 'O' 'O' 'N'
 'N' 'N' 'N' 'O' 'N' 'O' 'O' 'A' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' '~' 'O'
 'N' 'N' 'N' 'N' 'O' 'N' 'A' 'N' 'O' 'O' 'N' 'N' '~' 'N' 'N' 'O' 'A' 'N'
 'N' 'N' 'N' 'N' 'O' 'N' '~' 'O' 'O' 'N' 'O' 'N' 'A' 'O' 'O' 'N' 'N' 'N'
 'O' 'O' 'O' 'A' 'O' 'N' 'N' 'O' 'N' 'N' 'N' 'A' 'N' 'N' 'N' 'O' 'N' 'N'
 'N' 'O' 'N' 'O' 'O' 'O' 'N' 'O' 'N' 'N' 'A' 'N' '~' 'A' 'N' 'N' 'O' 'N'
 'N' 'N' 'O' 'O' 'N' 'N' 'O' 'O' 'N' 'O' 'N' 'N' 'A' 'N' 'N' 'N' 'N' 'N'
 'A' 'O' '~' 'O' 'N' 'N' 'N' 'O' 'N' 'A' 'O' 'N' 'N

In [61]:
theMax = 0

for i in range(0,100):    
    #print(accuracy_score(test_labels, predict_list[i]))
    if(accuracy_score(test_labels, predict_list[i]) > theMax):
        #print(np.average(f1_score(test_labels, predictions, average=None)))
        theMax = np.average(f1_score(test_labels, predictions, average=None))
print(theMax)

0.550052149802


In [62]:
results = confusion_matrix(test_labels, predictions,labels=["A", "N", "O","~"])
print(results)

[[ 40  10  16   1]
 [ 12 396  59   5]
 [ 19  97 109   3]
 [  6   3   8   6]]


In [63]:
#print('Parameters currently in use:\n')
#print(rf.get_params())

In [64]:
'''
import seaborn as sn
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

pd.options.display.float_format = '{:.4f}'.format
sn.set(font_scale=1.5)
array = [[ 39,   9,  17,   2],
 [ 10, 395,  61,   6],
 [ 21,  98, 104,   5],
 [  6,   4,   4,   9]]
df_cm = pd.DataFrame(array, index = ["A","N","O","~"],
                  columns = ["A","N","O","~"])

df_cm = df_cm.round(4)
plt.figure(figsize = (10,7))
plt.xlabel("Perdicted")
plt.ylabel("Actual")
sn.heatmap(df_cm, annot=True)
plt.savefig("tuff222.jpg")
'''

'\nimport seaborn as sn\nimport pandas as pd\nimport matplotlib.pyplot as plt\n%matplotlib inline\n\npd.options.display.float_format = \'{:.4f}\'.format\nsn.set(font_scale=1.5)\narray = [[ 39,   9,  17,   2],\n [ 10, 395,  61,   6],\n [ 21,  98, 104,   5],\n [  6,   4,   4,   9]]\ndf_cm = pd.DataFrame(array, index = ["A","N","O","~"],\n                  columns = ["A","N","O","~"])\n\ndf_cm = df_cm.round(4)\nplt.figure(figsize = (10,7))\nplt.xlabel("Perdicted")\nplt.ylabel("Actual")\nsn.heatmap(df_cm, annot=True)\nplt.savefig("tuff222.jpg")\n'