In [188]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
import random 

theCsv["avg_bottle_dist_dim0"] =theCsv5["avg_bottle_dist_dim0"]
theCsv["sd_bottle_dist_dim0"] =theCsv5["sd_bottle_dist_dim0"]


#theCsv["avg_bottle_dist_dim0"] =theCsv6["avg_bottle_dist_dim0"]
#theCsv["sd_bottle_dist_dim0"] =theCsv6["sd_bottle_dist_dim0"]

theCsv["avg_bottle_dist_dim0"] =theCsv7["avg_bottle_dist_dim0"]
theCsv["sd_bottle_dist_dim0"] =theCsv7["sd_bottle_dist_dim0"]
118

['N', 'R', 'R', 'N', 'N', 'AF', 'N', 'R', 'N', 'AF', 'N', 'N', 'N', 'R', 'AF', 'AF', 'N', 'AF', 'N', 'N', 'N', 'R', 'R', 'R', 'AF', 'R', 'N', 'N', 'R', 'R', 'R', 'N', 'N', 'AF', 'N', 'R', 'N', 'R', 'R', 'AF', 'AF', 'N', 'R', 'R', 'N', 'N', 'R', 'N', 'N', 'R', 'AF', 'AF', 'N', 'R', 'R', 'AF', 'AF', 'N', 'N', 'N', 'N', 'N', 'AF', 'R', 'R', 'N', 'R', 'R', 'N', 'AF', 'AF', 'N', 'R', 'AF', 'R', 'R', 'AF', 'AF', 'R', 'R', 'AF', 'R', 'R', 'AF', 'N', 'N', 'N', 'AF', 'AF', 'AF', 'AF', 'R', 'N', 'AF', 'AF', 'AF', 'AF', 'N', 'R', 'N', 'N', 'AF', 'R', 'AF', 'N', 'R', 'N', 'AF', 'AF', 'R', 'N', 'R', 'R', 'R', 'AF', 'AF', 'AF', 'N', 'R', 'R', 'N', 'N', 'AF', 'R', 'N', 'N', 'R', 'AF', 'R', 'R', 'N', 'R', 'N', 'N', 'R', 'N', 'N', 'N', 'AF', 'N', 'N', 'AF', 'N', 'N', 'R', 'N', 'AF', 'R', 'N', 'N', 'R', 'R', 'AF', 'AF', 'R', 'AF', 'N', 'R', 'N', 'N', 'AF', 'AF', 'N', 'R', 'AF', 'N', 'AF', 'AF', 'R', 'AF', 'AF', 'AF', 'R', 'R', 'N', 'N', 'R', 'N', 'N', 'AF', 'N', 'AF', 'R', 'R', 'R', 'AF', 'AF', 'R', 'AF', 'AF', 'R', 'R', 'N', 'AF', 'R', 'AF', 'R', 'AF']

['N', 'R', 'R', 'N', 'N', 'AF', 'N', 'R', 'N', 'AF', 'N', 'N', 'N', 'R', 'AF', 'AF', 'N', 'AF', 'N', 'N', 'N', 'R', 'R', 'R', 'AF', 'R', 'N', 'N', 'R', 'R', 'R', 'N', 'N', 'AF', 'N', 'R', 'N', 'R', 'R', 'AF', 'AF', 'N', 'R', 'R', 'N', 'N', 'R', 'N', 'N', 'R', 'AF', 'AF', 'N', 'R', 'R', 'AF', 'AF', 'N', 'N', 'N', 'N', 'N', 'AF', 'R', 'R', 'N', 'R', 'R', 'N', 'AF', 'AF', 'N', 'R', 'AF', 'R', 'R', 'AF', 'AF', 'R', 'R', 'AF', 'R', 'R', 'AF', 'N', 'N', 'N', 'AF', 'AF', 'AF', 'AF', 'R', 'N', 'AF', 'AF', 'AF', 'AF', 'N', 'R', 'N', 'N', 'AF', 'R', 'AF', 'N', 'R', 'N', 'AF', 'AF', 'R', 'N', 'R', 'R', 'R', 'AF', 'AF', 'AF', 'N', 'R', 'R', 'N', 'N', 'AF', 'R', 'N', 'N', 'R', 'AF', 'R', 'R', 'N', 'R', 'N', 'N', 'R', 'N', 'N', 'N', 'AF', 'N', 'N', 'AF', 'N', 'N', 'R', 'N', 'AF', 'R', 'N', 'N', 'R', 'R', 'AF', 'AF', 'R', 'AF', 'N', 'R', 'N', 'N', 'AF', 'AF', 'N', 'R', 'AF', 'N', 'AF', 'AF', 'R', 'AF', 'AF', 'AF', 'R', 'R', 'N', 'N', 'R', 'N', 'N', 'AF', 'N', 'AF', 'R', 'R', 'R', 'AF', 'AF', 'R', 'AF', 'AF', 'R', 'R', 'N', 'AF', 'R', 'AF', 'R', 'AF']


In [189]:
theTotal = []
classDict = {}
lineCount = 0

x = open("REFERENCE-v3.csv")
for line in x:
    line = line.strip()
    a,b = line.split(",")
    theTotal.append(b)
    
    

  
#theFrame = {"mean":[],"std_dev":[],"theClass":[]}

theCsv = pd.read_csv("SD_matrix_8528_new_index.csv", index_col=0)
theCsv1 = pd.read_csv("Mean_matrix_8528.csv",index_col=0)
theCsv11 = pd.read_csv("Skew_matrix_8528.csv",index_col=0)
theCsv111 = pd.read_csv("Kurt_matrix_8528.csv",index_col=0)

theCsv2 = pd.read_csv("0_8528_Organized_Mean_sd_dimension_1.csv",index_col=0)
theCsv3 = pd.read_csv("0_8528_Organized_Mean_sd_dimension_2.csv",index_col=0)
theCsv4 = pd.read_csv("0-8528sum_of_lifetimes.csv",index_col=0)
#0-8528_sd_lifetimes.csv
theCsv5 = pd.read_csv("0_8528_skew_lifetimes_dim_1_2.csv",index_col=0)
theCsv6 = pd.read_csv("0_8528_Organized_Mean_sd_dimension_0.csv",index_col=0)
theCsv7 = pd.read_csv("0_8528_diagdist_mean_sd_dim12.csv",index_col=0)
#print(theCsv6["0"])
theCsv8 = pd.read_csv("0_8528_number_pts_dim_0_1_2.csv",index_col=0)
theCsv9 = pd.read_csv("0-8528_sd_lifetimes.csv",index_col=0)
'''
theCsv2 = pd.read_csv("Mean_sd_dimension_1.csv",index_col=0)
theCsv3 = pd.read_csv("Mean_sd_dimension_2.csv",index_col=0)

theCsv5 = pd.read_csv("Maximum_lifetimes_all_dims.csv",index_col=0)


theCsv9 = pd.read_csv("number_of_births_deaths_dim1.csv",index_col=0)
theCsv10 = pd.read_csv("number_of_births_deaths_dim2.csv",index_col=0)
theCsv11 = pd.read_csv("skewness_birth_dim012.csv",index_col=0)
theCsv12 = pd.read_csv("skewness_death_dim012.csv",index_col=0)
theCsv13 = pd.read_csv("a.csv",index_col=0)
theCsv14 = pd.read_csv("Total_matrix_RR_interval_2392.csv",index_col=0)
theCsv15 = pd.read_csv("rr_normal.csv",index_col=0)
theCsv16 = pd.read_csv("rr_R.csv",index_col=0)
'''
#theCsv8 = pd.read_csv("reduced_bottleneck_ave_sd_dist_dim2.csv",index_col=0)
#bigData = theCsv.append(theCsv2, ignore_index=True)

#print(bigData)

aList = []
aList2 = []
aList3 = []
for i in range(0,200):
    aList.append("N")
    aList2.append(0)
    aList3.append(0)

for i in range(0,200):
    aList.append("AF")
    aList2.append(1)
    aList3.append(0)
    
for i in range(0,200):
    aList.append("R")
    aList2.append(0)
    aList3.append(1)

#theCsv["Normal"] = np.asarray(aList)
#theCsv["AF"] = np.asarray(aList2)
#theCsv["Random"] = np.asarray(aList3)
#### make dataframe 
###

In [190]:
#theCsv

In [191]:
#theCsv2.loc[599] =[0,0,0,0]
#theCsv2.loc[600] =[0,0,0,0]
#theCsv2
#bigdata = pd.concat([theCsv, theCsv2])


#print(theCsv3["Means_dim2_birth"])

#theCsv["RR_AF_mean"] = theCsv14["0"]
#theCsv["RR_AF_SD"] = theCsv14["1"]
#theCsv["RR_AF_Skew"] = theCsv14["3"]

#theCsv["sd_life_dim1"] =theCsv5["sd_life_dim1"]
#theCsv["sd_life_dim2"] =theCsv5["sd_life_dim2"]
#theCsv["RR_top"] =theCsv6["0"]
theCsv["Mean_RR"] = theCsv1["0"]
theCsv["Skew_RR"] = theCsv11["0"]
theCsv["Kurt_RR"] = theCsv111["0"]

theCsv["Means_dim1_birth"] = theCsv6["Means_dim0_birth"]
theCsv["Means_dim1_death"] = theCsv6["Means_dim0_birth"]
theCsv["sd_dim1_birth"] = theCsv6["sd_dim0_birth"]
theCsv["sd_dim1_death"] =theCsv6["sd_dim0_death"]

theCsv["Means_dim1_birth"] = theCsv2["Means_dim1_birth"]
theCsv["Means_dim1_death"] = theCsv2["Means_dim1_birth"]
theCsv["sd_dim1_birth"] = theCsv2["sd_dim1_birth"]
theCsv["sd_dim1_death"] =theCsv2["sd_dim1_death"]


#theCsv["Means_dim2_birth"] = theCsv3["Means_dim2_birth"]
theCsv["Means_dim2_death"] = theCsv3["Means_dim2_birth"]
theCsv["sd_dim2_birth"] = theCsv3["sd_dim2_birth"]
theCsv["sd_dim2_death"] =theCsv3["sd_dim2_death"]



#theCsv["Lifetime_dim0"] = theCsv4["Lifetime_dim0"]
theCsv["Lifetime_dim1"] = theCsv4["Lifetime_dim1"]
theCsv["Lifetime_dim2"] =theCsv4["Lifetime_dim2"]




#theCsv["V1"] =theCsv5["V2"]
#theCsv["sd_bottle_dist_dim0"] =theCsv5["Max_life_dim1"]

#theCsv["sd_life_dim1"] =theCsv5["sd_life_dim1"]
theCsv["skew_life_dim0"] =theCsv5["skew_life_dim0"]
theCsv["skew_life_dim1"] =theCsv5["skew_life_dim1"]
theCsv["skew_life_dim2"] =theCsv5["skew_life_dim2"]

#theCsv["avg_dist_dim2"] =theCsv7["avg_dist_dim2"]
theCsv["avg_dist_dim2"] =theCsv7["sd_dist_dim1"]

#theCsv["num_dim0"] = theCsv8["num_pts_dim0"]
theCsv["num_dim1"] = theCsv8["num_pts_dim1"]
#theCsv["num_dim2"] = theCsv8["num_pts_dim2"]


y = open("0-8528_sd_lifetimes.csv")

aList = []
aList2 =[]
count = 0
for line in y:
    if(count != 0):
        line = line.strip()
        a,b,c,d = line.split(",")
        aList.append(b)
        aList2.append(c)
    count +=  1
theCsv["sd_life_dim1"] = np.array(aList)
theCsv["sd_life_dim2"] = np.array(aList2)


'''
#theCsv["RR_top"] 
#theCsv["RR_top"][8528] = 1000
#8528

#theCsv["avg_bottle_dist_dim1"] =theCsv5["Max_life_dim0"]
#theCsv["sd_bottle_dist_dim1"] =theCsv6["V2"]

#
#theCsv["sd_bottle_dist_dim2"] =theCsv7["V2"]

#theCsv["num_dim0"] = theCsv8["x"]
#theCsv["num_dim1"] = theCsv9["x"]
#theCsv["num_dim2"] = theCsv10["x"]

#theCsv["num_dim1"] = theCsv10["x"]

#theCsv["skew_death1"] =theCsv12["skew.death.dim1"]
#theCsv["skew_death2"] =theCsv12["skew.death.dim2"]
#theCsv["skew_death0"] =theCsv12["skew.death.dim0"]


theCsv["skew_birth1"] = theCsv11["skew.birth.dim1"]
#theCsv["skew_birth2"] = theCsv11["skew.birth.dim2"]
print(len(theCsv["skew_birth1"]))

theCsv["num_per0"] = theCsv14["0"]
theCsv["num_per1"] = theCsv14["1"]
theCsv["num_per2"] = theCsv14["2"]
theCsv["num_per2"] = theCsv14["3"]



#theCsv["RR_R_mean"] = theCsv16["0"]
#print(theCsv)
#theCsv
#print(np.isnan(theCsv))

#theCsv["num_per0"][1956] = 1000
#theCsv["num_per1"][1956] = 1000
#theCsv["num_per2"][1956] = 1000
print(len(theTotal))
'''

print(theCsv)
theCsv["Normal"] = theTotal
#theCsv
#print(theCsv)
#print(theTotal)
theCsv.fillna(1000)
theCsv.replace(np.inf, 1000)

#print(np.where(theCsv.values >= np.finfo(np.float64).max))
#theCsv
#theCsv = theCsv.loc[:, ~theCsv.columns.str.contains('^Unnamed')]


#theCsv22 = theCsv.isnull().any


#for i in range(0,8529):
#    if(theCsv22["RR_top"][i] != True):
#        print(i)








#print(theCsv["RR_top"])
theCsv


               0     Mean_RR   Skew_RR    Kurt_RR  Means_dim1_birth  \
1       9.577564  228.000000  0.124222  -1.162912          1.309917   
2      87.331613  246.205882 -1.022362  -0.724066          0.714953   
3      27.370830  217.387500 -3.744155  15.809914          0.699906   
4      49.270636  278.733333  0.458097  -1.097738          0.796660   
5      65.337020  161.192661  1.201349   0.092824          1.430684   
6      19.667469  309.925926 -1.906248   2.957520          0.477725   
7      15.158065  286.482759 -0.421215  -0.816089          0.669206   
8      47.195133  257.176471 -1.862569   3.125275          0.904354   
9      31.578818  187.577778  0.445735  -0.344021          1.202949   
10      6.863423  275.809524 -0.233679  -0.736853          0.561889   
11      4.524061  254.058823 -0.875039   1.047385          0.795387   
12     10.817183  267.387097 -2.427412   4.358649          0.391169   
13      6.200673  191.772727 -1.714995   5.582406          1.455836   
14    

0     Mean_RR   Skew_RR    Kurt_RR  Means_dim1_birth  \
1       9.577564  228.000000  0.124222  -1.162912          1.309917   
2      87.331613  246.205882 -1.022362  -0.724066          0.714953   
3      27.370830  217.387500 -3.744155  15.809914          0.699906   
4      49.270636  278.733333  0.458097  -1.097738          0.796660   
5      65.337020  161.192661  1.201349   0.092824          1.430684   
6      19.667469  309.925926 -1.906248   2.957520          0.477725   
7      15.158065  286.482759 -0.421215  -0.816089          0.669206   
8      47.195133  257.176471 -1.862569   3.125275          0.904354   
9      31.578818  187.577778  0.445735  -0.344021          1.202949   
10      6.863423  275.809524 -0.233679  -0.736853          0.561889   
11      4.524061  254.058823 -0.875039   1.047385          0.795387   
12     10.817183  267.387097 -2.427412   4.358649          0.391169   
13      6.200673  191.772727 -1.714995   5.582406          1.455836   
14     24.367191  322.200000 -0.097570  -1.210753          1.259250   
15     60.248850  192.724138  0.082261  -0.886646          1.442371   
16     26.584723  214.050000 -4.423269  21.018242          1.397486   
17      3.943955  120.472222 -0.331484  -0.467831          0.634150   
18      9.818845  335.083333 -0.675574  -0.262612          0.348245   
19     27.368149  237.369565 -2.696528   8.603217          0.579889   
20     17.515390  224.459460 -2.853643  12.547024          0.783149   
21      5.629288  281.666667 -0.195124  -1.369373          0.545134   
22    123.863549  204.025641  2.792330   9.143628          1.625805   
23     30.003172  246.470588 -2.927493   8.282013          0.956149   
24     54.051054  245.205882 -2.130191   3.260827          1.198832   
25      4.790909  295.392857 -0.209853  -1.202287          1.247525   
26      2.556897  309.592593 -0.233592  -0.836577          0.463284   
27     35.892559  195.162791  0.701581  -0.110116          0.685037   
28      2.207793  281.887097  0.098095  -0.354220          1.304983   
29      5.179043  176.395833  0.968991   0.695708          0.536057   
30    100.617249  282.147541 -0.259487  -1.586383          1.301627   
...          ...         ...       ...        ...               ...   
8499   22.070323  181.085106 -1.687301   1.726986          0.391840   
8500   17.770535  148.034483  0.298034  -1.342477          0.982664   
8501   43.340895  278.951613  2.538419  13.558142          0.791422   
8502    9.747079  275.833333 -0.304807  -0.545703          0.520663   
8503    4.875741  221.263158  0.357836  -0.333566          1.586060   
8504   10.539498  225.605263 -1.840270   6.026760          1.391537   
8505   47.014478  236.833333 -2.842803   6.563341          1.625233   
8506   43.173598  290.620690 -4.902705  22.725081          1.301444   
8507    6.910835  274.047619 -0.790664   0.669538          0.683359   
8508   12.070067  258.468750 -0.391080  -0.465915          0.581381   
8509   41.532710  253.060606 -3.738825  12.672201          0.505467   
8510    1.023914  173.540000 -0.778662   0.299092          1.269203   
8511    4.948677  229.324324 -3.055033  13.117009          0.888330   
8512   26.318546  288.241379 -0.349390   0.117728          0.556039   
8513   27.488561  206.293103 -3.310272   9.808184          1.337732   
8514   28.510739  190.933333  0.670719  -0.187877          0.926117   
8515   15.951397  215.256410 -0.531143  -0.914933          0.560705   
8516   65.512301  377.954545 -3.567989  12.265397          0.545653   
8517    7.752664  250.117647 -0.325151  -0.546809          1.150507   
8518   31.350939  292.107143 -0.229763  -1.401931          2.262848   
8519    8.692270  233.333333 -0.369130  -1.210750          1.484348   
8520   25.517759  299.578947 -3.912341  20.897289          0.577209   
8521   63.932992  364.150000  0.093834  -0.937738          0.513927   
8522    3.077573  248.617647 -0.128864  -0.968426          1.611273   
8523   52.168288  254.968750  0.074747 

In [192]:
theCsv
theCsv_sorted = theCsv.sort_values(by='Normal')

print(theCsv_sorted["Normal"][1])
theL = []
normList = []
oList =[]
aaList = []
noiseList =[]
for i in range(1,8529):
    if(theCsv["Normal"][i] == "~"):
        noiseList.append(i)
    elif(theCsv["Normal"][i]== "A"):
        aaList.append(i)
    elif(theCsv["Normal"][i] == "O"):
        oList.append(i)
    else:
        normList.append(i)
        
        
normSamp = np.random.choice(normList, len(noiseSamp),replace=False)
aaSamp = np.random.choice(aaList, len(noiseSamp),replace=False)
oSamp = np.random.choice(oList,len(noiseSamp),replace=False)
noiseSamp = np.random.choice(noiseList,len(noiseSamp),replace=False)

#theCsv = theCsv.set_index(theL)

#print(len(normSamp))
#print(len(aaSamp))
#print(len(oSamp))
#print(len(noiseSamp))

random.Random(500)

theFinList = normSamp.tolist() + aaSamp.tolist() + oSamp.tolist() + noiseSamp.tolist()
#print(len(theFinList))

        
theTrain =  theCsv.drop(theFinList)
#print(list(set([x for x in theFinList if a.count(x) > 1])))

print(theCsv.shape)
print(theTrain.shape)
theTest = theCsv[~theCsv.index.isin(theTrain.index)]
#print(theCsv[~theCsv.index.isin(theTrain.index)].shape)
theTrain.shape

bal_train_labels = np.array(theTest["Normal"])
bal_test_labels = np.array(theTrain["Normal"])
theTest = theTest.drop("Normal",axis=1)
theTrain = theTrain.drop("Normal",axis=1)
theTempp = theTrain
theTrain = theTest
theTest = theTempp

N
(8528, 21)
(7528, 21)


In [193]:
### code from meduim torwards data scienec example
# Labels are the values we want to pred

labels = np.array(theCsv["Normal"])

# Remove the labels from the features
# axis 1 refers to the columns
theCsv = theCsv.drop('Normal', axis = 1)
#theCsv = theCsv.drop('AF', axis = 1)
#theCsv = theCsv.drop('Random', axis = 1)

# Saving feature names for later use
feature_list = list(theCsv.columns)

# Convert to numpy array
features = np.array(theCsv)


# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split


# Split the data into training and testing sets
train_features, test_features, train_labels, test_labels = train_test_split(theCsv, labels, test_size = 0.11726, random_state = 42)


print(test_labels.shape)

(1000,)


In [194]:
# Import the model we are using
#from sklearn.ensemble import RandomForest
predict_list = []
# Instantiate model with 1000 decision trees
for i in range(0,1):
    #rf = RandomForestClassifier(bootstrap=True,max_depth=20,max_features="sqrt",min_samples_leaf=4,min_samples_split=10,n_estimators=50,random_state=118)
    rf = RandomForestClassifier(bootstrap=True,max_depth=10,max_features="sqrt",min_samples_leaf=1,min_samples_split=5,n_estimators=600,random_state=40,class_weight="balanced")

#rf = RandomForestClassifier(bootstrap=True,max_depth=10,max_features="sqrt",min_samples_leaf=1,min_samples_split=5,n_estimators=600,random_state=42)

    

# Train the model on training data
    rf.fit(theTrain, bal_train_labels)

    predictions = rf.predict(theTest)
    predict_list.append(predictions)

In [195]:
print(theTrain)

                0      Mean_RR      Skew_RR      Kurt_RR  Means_dim1_birth  \
2       87.331613   246.205882    -1.022362    -0.724066          0.714953   
12      10.817183   267.387097    -2.427412     4.358649          0.391169   
15      60.248850   192.724138     0.082261    -0.886646          1.442371   
22     123.863549   204.025641     2.792330     9.143628          1.625805   
34      88.363584   255.242424    -1.062366    -0.568915          1.737288   
39      40.889842   267.387097    -3.217955     9.244766          1.164053   
41      55.489087   224.526316    -0.004331     0.018568          2.438303   
46       6.027828   191.727273    -1.432528     0.959288          1.605899   
53      86.332710   285.142857    -1.145103     0.008854          0.482945   
56      46.422744   144.784314     0.518099     1.596732          2.513323   
64       3.534652   221.921053    -0.267285    -1.055223          0.680324   
76       5.753055   219.184211     0.941406     0.026664        

In [196]:
print(predictions)

['N' 'N' 'A' ..., 'O' 'N' 'N']


In [197]:
print(test_labels)

['N' 'N' 'N' 'O' 'O' 'N' 'O' 'N' 'N' 'N' 'N' 'N' 'N' 'O' 'N' '~' 'N' 'N'
 'O' 'O' 'N' 'O' 'N' 'O' 'A' 'O' '~' 'N' 'N' 'O' 'N' 'O' 'N' 'N' 'O' 'O'
 'N' 'N' 'N' 'N' 'N' 'N' 'O' 'N' 'O' 'A' 'N' 'N' 'N' 'A' 'N' 'O' 'N' 'N'
 'A' 'N' 'N' 'N' 'N' 'O' 'N' 'O' 'N' 'O' 'A' 'O' 'O' 'N' 'N' 'N' 'N' 'O'
 'N' 'N' 'N' 'N' 'N' '~' 'O' 'A' 'N' 'N' 'O' 'A' 'O' 'N' 'N' 'O' 'N' 'A'
 'N' 'O' 'A' 'N' 'N' 'N' 'O' 'N' 'O' 'O' 'N' 'N' 'N' 'N' 'O' 'N' '~' 'A'
 'N' 'N' 'N' 'N' '~' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'A' 'N'
 'N' 'N' 'N' 'O' 'O' 'N' 'N' 'N' 'N' 'N' 'N' 'O' 'N' 'O' 'N' 'N' 'N' 'N'
 'N' 'N' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'N' 'O' 'N' 'O' 'N' 'A' 'N' 'N' 'A'
 'N' 'O' 'A' 'O' 'N' 'N' 'O' 'N' 'A' 'N' 'N' 'N' 'O' 'N' 'O' 'N' 'N' 'N'
 'N' 'N' 'N' 'O' 'O' 'A' 'O' 'A' 'O' 'O' 'A' 'O' 'O' 'N' 'O' 'N' 'N' 'N'
 'N' 'N' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'O' 'N' 'A' 'O'
 'N' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'O' 'O' 'O' 'N' 'A' 'N'
 'O' 'A' 'N' 'O' 'O' 'A' 'N' 'A' 'N' 'N' 'N' 'N' 'N

In [198]:
theMax = 0
for i in range(0,1):    
    if(accuracy_score(bal_test_labels, predict_list[i]) > theMax):
        theMax = np.average(f1_score(bal_test_labels, predictions, average=None))
print(theMax)

0.593659374585


In [199]:
results = confusion_matrix(bal_test_labels, predictions,labels=["A", "N", "O","~"])
print(results)

[[ 395    7   56   50]
 [   7 4345  267  207]
 [ 359   93 1440  273]
 [   0    2    3   24]]


In [200]:
#print('Parameters currently in use:\n')
#print(rf.get_params())

In [201]:



var1 = 36/(29+28)
var2 = 48/(31+39)
var3 = 112/(73+66)

print((var1+var2+var3)/3)

0.7076828762553866
