In [65]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score

theCsv["avg_bottle_dist_dim0"] =theCsv5["avg_bottle_dist_dim0"]
theCsv["sd_bottle_dist_dim0"] =theCsv5["sd_bottle_dist_dim0"]


#theCsv["avg_bottle_dist_dim0"] =theCsv6["avg_bottle_dist_dim0"]
#theCsv["sd_bottle_dist_dim0"] =theCsv6["sd_bottle_dist_dim0"]

theCsv["avg_bottle_dist_dim0"] =theCsv7["avg_bottle_dist_dim0"]
theCsv["sd_bottle_dist_dim0"] =theCsv7["sd_bottle_dist_dim0"]
118

['N', 'R', 'R', 'N', 'N', 'AF', 'N', 'R', 'N', 'AF', 'N', 'N', 'N', 'R', 'AF', 'AF', 'N', 'AF', 'N', 'N', 'N', 'R', 'R', 'R', 'AF', 'R', 'N', 'N', 'R', 'R', 'R', 'N', 'N', 'AF', 'N', 'R', 'N', 'R', 'R', 'AF', 'AF', 'N', 'R', 'R', 'N', 'N', 'R', 'N', 'N', 'R', 'AF', 'AF', 'N', 'R', 'R', 'AF', 'AF', 'N', 'N', 'N', 'N', 'N', 'AF', 'R', 'R', 'N', 'R', 'R', 'N', 'AF', 'AF', 'N', 'R', 'AF', 'R', 'R', 'AF', 'AF', 'R', 'R', 'AF', 'R', 'R', 'AF', 'N', 'N', 'N', 'AF', 'AF', 'AF', 'AF', 'R', 'N', 'AF', 'AF', 'AF', 'AF', 'N', 'R', 'N', 'N', 'AF', 'R', 'AF', 'N', 'R', 'N', 'AF', 'AF', 'R', 'N', 'R', 'R', 'R', 'AF', 'AF', 'AF', 'N', 'R', 'R', 'N', 'N', 'AF', 'R', 'N', 'N', 'R', 'AF', 'R', 'R', 'N', 'R', 'N', 'N', 'R', 'N', 'N', 'N', 'AF', 'N', 'N', 'AF', 'N', 'N', 'R', 'N', 'AF', 'R', 'N', 'N', 'R', 'R', 'AF', 'AF', 'R', 'AF', 'N', 'R', 'N', 'N', 'AF', 'AF', 'N', 'R', 'AF', 'N', 'AF', 'AF', 'R', 'AF', 'AF', 'AF', 'R', 'R', 'N', 'N', 'R', 'N', 'N', 'AF', 'N', 'AF', 'R', 'R', 'R', 'AF', 'AF', 'R', 'AF', 'AF', 'R', 'R', 'N', 'AF', 'R', 'AF', 'R', 'AF']

['N', 'R', 'R', 'N', 'N', 'AF', 'N', 'R', 'N', 'AF', 'N', 'N', 'N', 'R', 'AF', 'AF', 'N', 'AF', 'N', 'N', 'N', 'R', 'R', 'R', 'AF', 'R', 'N', 'N', 'R', 'R', 'R', 'N', 'N', 'AF', 'N', 'R', 'N', 'R', 'R', 'AF', 'AF', 'N', 'R', 'R', 'N', 'N', 'R', 'N', 'N', 'R', 'AF', 'AF', 'N', 'R', 'R', 'AF', 'AF', 'N', 'N', 'N', 'N', 'N', 'AF', 'R', 'R', 'N', 'R', 'R', 'N', 'AF', 'AF', 'N', 'R', 'AF', 'R', 'R', 'AF', 'AF', 'R', 'R', 'AF', 'R', 'R', 'AF', 'N', 'N', 'N', 'AF', 'AF', 'AF', 'AF', 'R', 'N', 'AF', 'AF', 'AF', 'AF', 'N', 'R', 'N', 'N', 'AF', 'R', 'AF', 'N', 'R', 'N', 'AF', 'AF', 'R', 'N', 'R', 'R', 'R', 'AF', 'AF', 'AF', 'N', 'R', 'R', 'N', 'N', 'AF', 'R', 'N', 'N', 'R', 'AF', 'R', 'R', 'N', 'R', 'N', 'N', 'R', 'N', 'N', 'N', 'AF', 'N', 'N', 'AF', 'N', 'N', 'R', 'N', 'AF', 'R', 'N', 'N', 'R', 'R', 'AF', 'AF', 'R', 'AF', 'N', 'R', 'N', 'N', 'AF', 'AF', 'N', 'R', 'AF', 'N', 'AF', 'AF', 'R', 'AF', 'AF', 'AF', 'R', 'R', 'N', 'N', 'R', 'N', 'N', 'AF', 'N', 'AF', 'R', 'R', 'R', 'AF', 'AF', 'R', 'AF', 'AF', 'R', 'R', 'N', 'AF', 'R', 'AF', 'R', 'AF']


In [66]:
theTotal = []
classDict = {}
lineCount = 0

x = open("REFERENCE-v3.csv")
for line in x:
    line = line.strip()
    a,b = line.split(",")
    theTotal.append(b)
    
    

  
#theFrame = {"mean":[],"std_dev":[],"theClass":[]}

theCsv = pd.read_csv("0_8528_Organized_Mean_sd_dimension_0.csv", index_col=0)
#theCsv1 = pd.read_csv("Mean_matrix_8528.csv",index_col=0)
#theCsv11 = pd.read_csv("Skew_matrix_8528.csv",index_col=0)
#theCsv111 = pd.read_csv("Kurt_matrix_8528.csv",index_col=0)

theCsv2 = pd.read_csv("0_8528_Organized_Mean_sd_dimension_1.csv",index_col=0)
theCsv3 = pd.read_csv("0_8528_Organized_Mean_sd_dimension_2.csv",index_col=0)
theCsv4 = pd.read_csv("0-8528sum_of_lifetimes.csv",index_col=0)
#0-8528_sd_lifetimes.csv
theCsv5 = pd.read_csv("0_8528_skew_lifetimes_dim_1_2.csv",index_col=0)
#theCsv6 = pd.read_csv("0_8528_Organized_Mean_sd_dimension_0.csv",index_col=0)
theCsv7 = pd.read_csv("0_8528_diagdist_mean_sd_dim12.csv",index_col=0)
#print(theCsv6["0"])
theCsv8 = pd.read_csv("0_8528_number_pts_dim_0_1_2.csv",index_col=0)
theCsv9 = pd.read_csv("0-8528_sd_lifetimes.csv",index_col=0)
'''
theCsv2 = pd.read_csv("Mean_sd_dimension_1.csv",index_col=0)
theCsv3 = pd.read_csv("Mean_sd_dimension_2.csv",index_col=0)

theCsv5 = pd.read_csv("Maximum_lifetimes_all_dims.csv",index_col=0)


theCsv9 = pd.read_csv("number_of_births_deaths_dim1.csv",index_col=0)
theCsv10 = pd.read_csv("number_of_births_deaths_dim2.csv",index_col=0)
theCsv11 = pd.read_csv("skewness_birth_dim012.csv",index_col=0)
theCsv12 = pd.read_csv("skewness_death_dim012.csv",index_col=0)
theCsv13 = pd.read_csv("a.csv",index_col=0)
theCsv14 = pd.read_csv("Total_matrix_RR_interval_2392.csv",index_col=0)
theCsv15 = pd.read_csv("rr_normal.csv",index_col=0)
theCsv16 = pd.read_csv("rr_R.csv",index_col=0)
'''
#theCsv8 = pd.read_csv("reduced_bottleneck_ave_sd_dist_dim2.csv",index_col=0)
#bigData = theCsv.append(theCsv2, ignore_index=True)

#print(bigData)

aList = []
aList2 = []
aList3 = []
for i in range(0,200):
    aList.append("N")
    aList2.append(0)
    aList3.append(0)

for i in range(0,200):
    aList.append("AF")
    aList2.append(1)
    aList3.append(0)
    
for i in range(0,200):
    aList.append("R")
    aList2.append(0)
    aList3.append(1)

#theCsv["Normal"] = np.asarray(aList)
#theCsv["AF"] = np.asarray(aList2)
#theCsv["Random"] = np.asarray(aList3)
#### make dataframe 
###

In [67]:
#theCsv

In [68]:
#theCsv2.loc[599] =[0,0,0,0]
#theCsv2.loc[600] =[0,0,0,0]
#theCsv2
#bigdata = pd.concat([theCsv, theCsv2])


#print(theCsv3["Means_dim2_birth"])

#theCsv["RR_AF_mean"] = theCsv14["0"]
#theCsv["RR_AF_SD"] = theCsv14["1"]
#theCsv["RR_AF_Skew"] = theCsv14["3"]

#theCsv["sd_life_dim1"] =theCsv5["sd_life_dim1"]
#theCsv["sd_life_dim2"] =theCsv5["sd_life_dim2"]
#theCsv["RR_top"] =theCsv6["0"]
'''
theCsv["Mean_RR"] = theCsv1["0"]
theCsv["Skew_RR"] = theCsv11["0"]
theCsv["Kurt_RR"] = theCsv111["0"]
theCsv["Means_dim1_birth"] = theCsv6["Means_dim0_birth"]
theCsv["Means_dim1_death"] = theCsv6["Means_dim0_birth"]
theCsv["sd_dim1_birth"] = theCsv6["sd_dim0_birth"]
theCsv["sd_dim1_death"] =theCsv6["sd_dim0_death"]
'''
theCsv["Means_dim1_birth"] = theCsv2["Means_dim1_birth"]
theCsv["Means_dim1_death"] = theCsv2["Means_dim1_birth"]
theCsv["sd_dim1_birth"] = theCsv2["sd_dim1_birth"]
theCsv["sd_dim1_death"] =theCsv2["sd_dim1_death"]


#theCsv["Means_dim2_birth"] = theCsv3["Means_dim2_birth"]
theCsv["Means_dim2_death"] = theCsv3["Means_dim2_birth"]
theCsv["sd_dim2_birth"] = theCsv3["sd_dim2_birth"]
theCsv["sd_dim2_death"] =theCsv3["sd_dim2_death"]



#theCsv["Lifetime_dim0"] = theCsv4["Lifetime_dim0"]
theCsv["Lifetime_dim1"] = theCsv4["Lifetime_dim1"]
theCsv["Lifetime_dim2"] =theCsv4["Lifetime_dim2"]




#theCsv["V1"] =theCsv5["V2"]
#theCsv["sd_bottle_dist_dim0"] =theCsv5["Max_life_dim1"]

#theCsv["sd_life_dim1"] =theCsv5["sd_life_dim1"]
theCsv["skew_life_dim0"] =theCsv5["skew_life_dim0"]
theCsv["skew_life_dim1"] =theCsv5["skew_life_dim1"]
theCsv["skew_life_dim2"] =theCsv5["skew_life_dim2"]

#theCsv["avg_dist_dim2"] =theCsv7["avg_dist_dim2"]
theCsv["avg_dist_dim2"] =theCsv7["sd_dist_dim1"]

#theCsv["num_dim0"] = theCsv8["num_pts_dim0"]
theCsv["num_dim1"] = theCsv8["num_pts_dim1"]
#theCsv["num_dim2"] = theCsv8["num_pts_dim2"]


y = open("0-8528_sd_lifetimes.csv")

aList = []
aList2 =[]
count = 0
for line in y:
    if(count != 0):
        line = line.strip()
        a,b,c,d = line.split(",")
        aList.append(b)
        aList2.append(c)
    count +=  1
theCsv["sd_life_dim1"] = np.array(aList)
#theCsv["sd_life_dim2"] = np.array(aList2)



#theCsv["RR_top"] 
#theCsv["RR_top"][8528] = 1000
#8528
'''
#theCsv["avg_bottle_dist_dim1"] =theCsv5["Max_life_dim0"]
#theCsv["sd_bottle_dist_dim1"] =theCsv6["V2"]

#
#theCsv["sd_bottle_dist_dim2"] =theCsv7["V2"]

#theCsv["num_dim0"] = theCsv8["x"]
#theCsv["num_dim1"] = theCsv9["x"]
#theCsv["num_dim2"] = theCsv10["x"]

#theCsv["num_dim1"] = theCsv10["x"]

#theCsv["skew_death1"] =theCsv12["skew.death.dim1"]
#theCsv["skew_death2"] =theCsv12["skew.death.dim2"]
#theCsv["skew_death0"] =theCsv12["skew.death.dim0"]


theCsv["skew_birth1"] = theCsv11["skew.birth.dim1"]
#theCsv["skew_birth2"] = theCsv11["skew.birth.dim2"]
print(len(theCsv["skew_birth1"]))

theCsv["num_per0"] = theCsv14["0"]
theCsv["num_per1"] = theCsv14["1"]
theCsv["num_per2"] = theCsv14["2"]
theCsv["num_per2"] = theCsv14["3"]



#theCsv["RR_R_mean"] = theCsv16["0"]
#print(theCsv)
#theCsv
#print(np.isnan(theCsv))

#theCsv["num_per0"][1956] = 1000
#theCsv["num_per1"][1956] = 1000
#theCsv["num_per2"][1956] = 1000
print(len(theTotal))
'''

print(theCsv)
theCsv["Normal"] = theTotal
#theCsv
#print(theCsv)
#print(theTotal)
theCsv.fillna(1000)
theCsv.replace(np.inf, 1000)

#print(np.where(theCsv.values >= np.finfo(np.float64).max))
#theCsv
#theCsv = theCsv.loc[:, ~theCsv.columns.str.contains('^Unnamed')]


#theCsv22 = theCsv.isnull().any


#for i in range(0,8529):
#    if(theCsv22["RR_top"][i] != True):
#        print(i)








#print(theCsv["RR_top"])
theCsv


      Means_dim0_birth  Means_dim0_death  sd_dim0_birth  sd_dim0_death  \
1                    0          0.532601              0       0.282795   
2                    0          0.503053              0       0.268632   
3                    0          0.379515              0       0.143459   
4                    0          0.425480              0       0.200396   
5                    0          1.112501              0       0.398162   
6                    0          0.272712              0       0.128959   
7                    0          0.266372              0       0.131238   
8                    0          0.479044              0       0.225049   
9                    0          0.850694              0       0.196218   
10                   0          0.394447              0       0.103590   
11                   0          0.513328              0       0.092833   
12                   0          0.213943              0       0.053455   
13                   0          0.4196

Means_dim0_birth  Means_dim0_death  sd_dim0_birth  sd_dim0_death  \
1                    0          0.532601              0       0.282795   
2                    0          0.503053              0       0.268632   
3                    0          0.379515              0       0.143459   
4                    0          0.425480              0       0.200396   
5                    0          1.112501              0       0.398162   
6                    0          0.272712              0       0.128959   
7                    0          0.266372              0       0.131238   
8                    0          0.479044              0       0.225049   
9                    0          0.850694              0       0.196218   
10                   0          0.394447              0       0.103590   
11                   0          0.513328              0       0.092833   
12                   0          0.213943              0       0.053455   
13                   0          0.419666              0       0.339170   
14                   0          0.778684              0       0.267724   
15                   0          0.964255              0       0.282923   
16                   0          0.740375              0       0.296588   
17                   0          0.468481              0       0.043781   
18                   0          0.219961              0       0.065375   
19                   0          0.428692              0       0.312847   
20                   0          0.499813              0       0.128485   
21                   0          0.284072              0       0.110296   
22                   0          0.779829              0       0.706482   
23                   0          0.681505              0       0.177760   
24                   0          0.726515              0       0.223643   
25                   0          0.832944              0       0.254777   
26                   0          0.283784              0       0.112200   
27                   0          0.417818              0       0.110033   
28                   0          0.839356              0       0.307597   
29                   0          0.287898              0       0.087946   
30                   0          0.781865              0       0.345267   
...                ...               ...            ...            ...   
8499                 0          0.255317              0       0.052975   
8500                 0          0.653313              0       0.183739   
8501                 0          0.539293              0       0.134033   
8502                 0          0.327118              0       0.109340   
8503                 0          0.715905              0       0.244639   
8504                 0          0.575618              0       0.256146   
8505                 0          1.092660              0       1.113471   
8506                 0          0.736041              0       0.851505   
8507                 0          0.437883              0       0.171491   
8508                 0          0.298362              0       0.072947   
8509                 0          0.328646              0       0.067609   
8510                 0          0.673225              0       0.312069   
8511                 0          0.408755              0       0.236967   
8512                 0          0.323928              0       0.140751   
8513                 0          0.822649              0       0.317638   
8514                 0          0.717188              0       0.147809   
8515                 0          0.435716              0       0.094211   
8516                 0          0.353864              0       0.153658   
8517                 0          0.792474              0       0.210492   
8518                 0          1.649009              0       0.430908   
8519                 0          0.790665              0       0.237330   
8520                 0          0.306428              0       0.169305   
8521      

In [69]:
### code from meduim torwards data scienec example
# Labels are the values we want to pred

labels = np.array(theCsv["Normal"])

# Remove the labels from the features
# axis 1 refers to the columns
theCsv = theCsv.drop('Normal', axis = 1)
#theCsv = theCsv.drop('AF', axis = 1)
#theCsv = theCsv.drop('Random', axis = 1)

# Saving feature names for later use
feature_list = list(theCsv.columns)

# Convert to numpy array
features = np.array(theCsv)


# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split


# Split the data into training and testing sets
train_features, test_features, train_labels, test_labels = train_test_split(theCsv, labels, test_size = 0.11726, random_state = 42)


print(test_labels.tolist())

['N', 'N', 'N', 'O', 'O', 'N', 'O', 'N', 'N', 'N', 'N', 'N', 'N', 'O', 'N', '~', 'N', 'N', 'O', 'O', 'N', 'O', 'N', 'O', 'A', 'O', '~', 'N', 'N', 'O', 'N', 'O', 'N', 'N', 'O', 'O', 'N', 'N', 'N', 'N', 'N', 'N', 'O', 'N', 'O', 'A', 'N', 'N', 'N', 'A', 'N', 'O', 'N', 'N', 'A', 'N', 'N', 'N', 'N', 'O', 'N', 'O', 'N', 'O', 'A', 'O', 'O', 'N', 'N', 'N', 'N', 'O', 'N', 'N', 'N', 'N', 'N', '~', 'O', 'A', 'N', 'N', 'O', 'A', 'O', 'N', 'N', 'O', 'N', 'A', 'N', 'O', 'A', 'N', 'N', 'N', 'O', 'N', 'O', 'O', 'N', 'N', 'N', 'N', 'O', 'N', '~', 'A', 'N', 'N', 'N', 'N', '~', 'N', 'N', 'N', 'O', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'A', 'N', 'N', 'N', 'N', 'O', 'O', 'N', 'N', 'N', 'N', 'N', 'N', 'O', 'N', 'O', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'O', 'N', 'N', 'N', 'N', 'O', 'N', 'O', 'N', 'A', 'N', 'N', 'A', 'N', 'O', 'A', 'O', 'N', 'N', 'O', 'N', 'A', 'N', 'N', 'N', 'O', 'N', 'O', 'N', 'N', 'N', 'N', 'N', 'N', 'O', 'O', 'A', 'O', 'A', 'O', 'O', 'A', 'O', 'O', 'N', 'O', 'N', 'N', 'N', 'N', 'N',

In [70]:
# Import the model we are using
#from sklearn.ensemble import RandomForest
predict_list = []
# Instantiate model with 1000 decision trees
for i in range(0,1):
    #rf = RandomForestClassifier(bootstrap=True,max_depth=20,max_features="sqrt",min_samples_leaf=4,min_samples_split=10,n_estimators=50,random_state=118)
    rf = RandomForestClassifier(bootstrap=True,max_depth=10,max_features="sqrt",min_samples_leaf=1,min_samples_split=5,n_estimators=600,random_state=40)

#rf = RandomForestClassifier(bootstrap=True,max_depth=10,max_features="sqrt",min_samples_leaf=1,min_samples_split=5,n_estimators=600,random_state=42)

    

# Train the model on training data
    rf.fit(train_features, train_labels)

    predictions = rf.predict(test_features)
    predict_list.append(predictions)

In [71]:
print(predictions)

['N' 'N' 'N' 'O' 'O' 'N' 'O' 'N' 'N' 'N' 'N' 'N' 'N' 'O' 'N' 'O' 'N' 'N'
 'O' 'O' 'N' 'O' 'N' 'O' 'O' 'O' 'A' 'N' 'N' 'O' 'N' 'O' 'N' 'N' 'O' 'O'
 'N' 'N' 'N' 'N' 'N' 'N' 'O' 'N' 'O' 'O' 'N' 'N' 'N' 'O' 'N' 'O' 'N' 'N'
 'O' 'N' 'N' 'N' 'N' 'O' 'N' 'O' 'N' 'O' 'O' 'O' 'O' 'N' 'N' 'N' 'N' 'O'
 'N' 'N' 'N' 'N' 'N' 'O' 'O' 'O' 'N' 'N' 'O' 'N' 'O' 'N' 'N' 'O' 'N' 'O'
 'N' 'O' 'O' 'N' 'N' 'N' 'O' 'N' 'O' 'O' 'N' 'N' 'N' 'N' 'O' 'N' 'O' 'O'
 'O' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'O' 'N'
 'N' 'N' 'N' 'O' 'O' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'N'
 'N' 'N' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'N' 'O' 'N' 'O' 'N' 'O' 'N' 'N' 'O'
 'N' 'O' 'O' 'O' 'N' 'N' 'O' 'N' 'O' 'N' 'N' 'O' 'O' 'N' 'O' 'N' 'N' 'N'
 'N' 'N' 'N' 'O' 'N' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'N' 'O' 'N' 'N' 'N'
 'N' 'N' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'O' 'N' 'O' 'O'
 'N' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'O' 'O' 'N' 'N' 'O' 'N'
 'O' 'A' 'N' 'O' 'O' 'O' 'N' 'O' 'N' 'N' 'N' 'N' 'N

In [72]:
print(test_labels)

['N' 'N' 'N' 'O' 'O' 'N' 'O' 'N' 'N' 'N' 'N' 'N' 'N' 'O' 'N' '~' 'N' 'N'
 'O' 'O' 'N' 'O' 'N' 'O' 'A' 'O' '~' 'N' 'N' 'O' 'N' 'O' 'N' 'N' 'O' 'O'
 'N' 'N' 'N' 'N' 'N' 'N' 'O' 'N' 'O' 'A' 'N' 'N' 'N' 'A' 'N' 'O' 'N' 'N'
 'A' 'N' 'N' 'N' 'N' 'O' 'N' 'O' 'N' 'O' 'A' 'O' 'O' 'N' 'N' 'N' 'N' 'O'
 'N' 'N' 'N' 'N' 'N' '~' 'O' 'A' 'N' 'N' 'O' 'A' 'O' 'N' 'N' 'O' 'N' 'A'
 'N' 'O' 'A' 'N' 'N' 'N' 'O' 'N' 'O' 'O' 'N' 'N' 'N' 'N' 'O' 'N' '~' 'A'
 'N' 'N' 'N' 'N' '~' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'A' 'N'
 'N' 'N' 'N' 'O' 'O' 'N' 'N' 'N' 'N' 'N' 'N' 'O' 'N' 'O' 'N' 'N' 'N' 'N'
 'N' 'N' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'N' 'O' 'N' 'O' 'N' 'A' 'N' 'N' 'A'
 'N' 'O' 'A' 'O' 'N' 'N' 'O' 'N' 'A' 'N' 'N' 'N' 'O' 'N' 'O' 'N' 'N' 'N'
 'N' 'N' 'N' 'O' 'O' 'A' 'O' 'A' 'O' 'O' 'A' 'O' 'O' 'N' 'O' 'N' 'N' 'N'
 'N' 'N' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'O' 'N' 'A' 'O'
 'N' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'O' 'N' 'N' 'N' 'O' 'O' 'O' 'N' 'A' 'N'
 'O' 'A' 'N' 'O' 'O' 'A' 'N' 'A' 'N' 'N' 'N' 'N' 'N

In [73]:
theMax = 0
for i in range(0,1):    
    if(accuracy_score(test_labels, predict_list[i]) > theMax):
        theMax = np.average(f1_score(test_labels, predictions, average=None))
print(theMax)

0.569012049939


In [74]:
results = confusion_matrix(test_labels, predictions,labels=["A", "N", "O","~"])
print(results)

[[ 12   4  72   1]
 [  0 596   7   0]
 [  5  20 248   2]
 [  2   5  20   6]]


In [75]:
#print('Parameters currently in use:\n')
#print(rf.get_params())

In [76]:



var1 = 36/(29+28)
var2 = 48/(31+39)
var3 = 112/(73+66)

print((var1+var2+var3)/3)

0.7076828762553866
