In [382]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score

theCsv["avg_bottle_dist_dim0"] =theCsv5["avg_bottle_dist_dim0"]
theCsv["sd_bottle_dist_dim0"] =theCsv5["sd_bottle_dist_dim0"]


#theCsv["avg_bottle_dist_dim0"] =theCsv6["avg_bottle_dist_dim0"]
#theCsv["sd_bottle_dist_dim0"] =theCsv6["sd_bottle_dist_dim0"]

theCsv["avg_bottle_dist_dim0"] =theCsv7["avg_bottle_dist_dim0"]
theCsv["sd_bottle_dist_dim0"] =theCsv7["sd_bottle_dist_dim0"]
118

['N', 'R', 'R', 'N', 'N', 'AF', 'N', 'R', 'N', 'AF', 'N', 'N', 'N', 'R', 'AF', 'AF', 'N', 'AF', 'N', 'N', 'N', 'R', 'R', 'R', 'AF', 'R', 'N', 'N', 'R', 'R', 'R', 'N', 'N', 'AF', 'N', 'R', 'N', 'R', 'R', 'AF', 'AF', 'N', 'R', 'R', 'N', 'N', 'R', 'N', 'N', 'R', 'AF', 'AF', 'N', 'R', 'R', 'AF', 'AF', 'N', 'N', 'N', 'N', 'N', 'AF', 'R', 'R', 'N', 'R', 'R', 'N', 'AF', 'AF', 'N', 'R', 'AF', 'R', 'R', 'AF', 'AF', 'R', 'R', 'AF', 'R', 'R', 'AF', 'N', 'N', 'N', 'AF', 'AF', 'AF', 'AF', 'R', 'N', 'AF', 'AF', 'AF', 'AF', 'N', 'R', 'N', 'N', 'AF', 'R', 'AF', 'N', 'R', 'N', 'AF', 'AF', 'R', 'N', 'R', 'R', 'R', 'AF', 'AF', 'AF', 'N', 'R', 'R', 'N', 'N', 'AF', 'R', 'N', 'N', 'R', 'AF', 'R', 'R', 'N', 'R', 'N', 'N', 'R', 'N', 'N', 'N', 'AF', 'N', 'N', 'AF', 'N', 'N', 'R', 'N', 'AF', 'R', 'N', 'N', 'R', 'R', 'AF', 'AF', 'R', 'AF', 'N', 'R', 'N', 'N', 'AF', 'AF', 'N', 'R', 'AF', 'N', 'AF', 'AF', 'R', 'AF', 'AF', 'AF', 'R', 'R', 'N', 'N', 'R', 'N', 'N', 'AF', 'N', 'AF', 'R', 'R', 'R', 'AF', 'AF', 'R', 'AF', 'AF', 'R', 'R', 'N', 'AF', 'R', 'AF', 'R', 'AF']

['N', 'R', 'R', 'N', 'N', 'AF', 'N', 'R', 'N', 'AF', 'N', 'N', 'N', 'R', 'AF', 'AF', 'N', 'AF', 'N', 'N', 'N', 'R', 'R', 'R', 'AF', 'R', 'N', 'N', 'R', 'R', 'R', 'N', 'N', 'AF', 'N', 'R', 'N', 'R', 'R', 'AF', 'AF', 'N', 'R', 'R', 'N', 'N', 'R', 'N', 'N', 'R', 'AF', 'AF', 'N', 'R', 'R', 'AF', 'AF', 'N', 'N', 'N', 'N', 'N', 'AF', 'R', 'R', 'N', 'R', 'R', 'N', 'AF', 'AF', 'N', 'R', 'AF', 'R', 'R', 'AF', 'AF', 'R', 'R', 'AF', 'R', 'R', 'AF', 'N', 'N', 'N', 'AF', 'AF', 'AF', 'AF', 'R', 'N', 'AF', 'AF', 'AF', 'AF', 'N', 'R', 'N', 'N', 'AF', 'R', 'AF', 'N', 'R', 'N', 'AF', 'AF', 'R', 'N', 'R', 'R', 'R', 'AF', 'AF', 'AF', 'N', 'R', 'R', 'N', 'N', 'AF', 'R', 'N', 'N', 'R', 'AF', 'R', 'R', 'N', 'R', 'N', 'N', 'R', 'N', 'N', 'N', 'AF', 'N', 'N', 'AF', 'N', 'N', 'R', 'N', 'AF', 'R', 'N', 'N', 'R', 'R', 'AF', 'AF', 'R', 'AF', 'N', 'R', 'N', 'N', 'AF', 'AF', 'N', 'R', 'AF', 'N', 'AF', 'AF', 'R', 'AF', 'AF', 'AF', 'R', 'R', 'N', 'N', 'R', 'N', 'N', 'AF', 'N', 'AF', 'R', 'R', 'R', 'AF', 'AF', 'R', 'AF', 'AF', 'R', 'R', 'N', 'AF', 'R', 'AF', 'R', 'AF']


In [383]:
theTotal = []
classDict = {}
lineCount = 0

x = open("REFERENCE-v3.csv")
for line in x:
    line = line.strip()
    a,b = line.split(",")
    theTotal.append(b)
    
    

  
#theFrame = {"mean":[],"std_dev":[],"theClass":[]}

theCsv = pd.read_csv("SD_matrix_8528_new_index.csv", index_col=0)
theCsv1 = pd.read_csv("Mean_matrix_8528.csv",index_col=0)
theCsv11 = pd.read_csv("Skew_matrix_8528.csv",index_col=0)
theCsv2 = pd.read_csv("0_8528_Organized_Mean_sd_dimension_1.csv",index_col=0)
theCsv3 = pd.read_csv("0_8528_Organized_Mean_sd_dimension_2.csv",index_col=0)
theCsv4 = pd.read_csv("0-8528sum_of_lifetimes.csv",index_col=0)
#0-8528_sd_lifetimes.csv
theCsv5 = pd.read_csv("0_8528_skew_lifetimes_dim_1_2.csv",index_col=0)
theCsv6 = pd.read_csv("0_8528_Organized_Mean_sd_dimension_0.csv",index_col=0)
theCsv7 = pd.read_csv("0_8528_diagdist_mean_sd_dim12.csv",index_col=0)
#print(theCsv6["0"])
theCsv8 = pd.read_csv("matrix_stats_cout_8000A08528.csv",index_col=0)
'''
theCsv2 = pd.read_csv("Mean_sd_dimension_1.csv",index_col=0)
theCsv3 = pd.read_csv("Mean_sd_dimension_2.csv",index_col=0)

theCsv5 = pd.read_csv("Maximum_lifetimes_all_dims.csv",index_col=0)


theCsv9 = pd.read_csv("number_of_births_deaths_dim1.csv",index_col=0)
theCsv10 = pd.read_csv("number_of_births_deaths_dim2.csv",index_col=0)
theCsv11 = pd.read_csv("skewness_birth_dim012.csv",index_col=0)
theCsv12 = pd.read_csv("skewness_death_dim012.csv",index_col=0)
theCsv13 = pd.read_csv("a.csv",index_col=0)
theCsv14 = pd.read_csv("Total_matrix_RR_interval_2392.csv",index_col=0)
theCsv15 = pd.read_csv("rr_normal.csv",index_col=0)
theCsv16 = pd.read_csv("rr_R.csv",index_col=0)
'''
#theCsv8 = pd.read_csv("reduced_bottleneck_ave_sd_dist_dim2.csv",index_col=0)
#bigData = theCsv.append(theCsv2, ignore_index=True)

#print(bigData)

aList = []
aList2 = []
aList3 = []
for i in range(0,200):
    aList.append("N")
    aList2.append(0)
    aList3.append(0)

for i in range(0,200):
    aList.append("AF")
    aList2.append(1)
    aList3.append(0)
    
for i in range(0,200):
    aList.append("R")
    aList2.append(0)
    aList3.append(1)

#theCsv["Normal"] = np.asarray(aList)
#theCsv["AF"] = np.asarray(aList2)
#theCsv["Random"] = np.asarray(aList3)
#### make dataframe 
###

In [384]:
#theCsv

In [385]:
#theCsv2.loc[599] =[0,0,0,0]
#theCsv2.loc[600] =[0,0,0,0]
#theCsv2
#bigdata = pd.concat([theCsv, theCsv2])


#print(theCsv3["Means_dim2_birth"])

#theCsv["RR_AF_mean"] = theCsv14["0"]
#theCsv["RR_AF_SD"] = theCsv14["1"]
#theCsv["RR_AF_Skew"] = theCsv14["3"]

#theCsv["sd_life_dim1"] =theCsv5["sd_life_dim1"]
#theCsv["sd_life_dim2"] =theCsv5["sd_life_dim2"]
#theCsv["RR_top"] =theCsv6["0"]
theCsv["Mean_RR"] = theCsv1["0"]
theCsv["Skew_RR"] = theCsv11["0"]
theCsv["Means_dim1_birth"] = theCsv6["Means_dim0_birth"]
theCsv["Means_dim1_death"] = theCsv6["Means_dim0_birth"]
theCsv["sd_dim1_birth"] = theCsv6["sd_dim0_birth"]
theCsv["sd_dim1_death"] =theCsv6["sd_dim0_death"]

theCsv["Means_dim1_birth"] = theCsv2["Means_dim1_birth"]
theCsv["Means_dim1_death"] = theCsv2["Means_dim1_birth"]
theCsv["sd_dim1_birth"] = theCsv2["sd_dim1_birth"]
theCsv["sd_dim1_death"] =theCsv2["sd_dim1_death"]


#theCsv["Means_dim2_birth"] = theCsv3["Means_dim2_birth"]
theCsv["Means_dim2_death"] = theCsv3["Means_dim2_birth"]
theCsv["sd_dim2_birth"] = theCsv3["sd_dim2_birth"]
theCsv["sd_dim2_death"] =theCsv3["sd_dim2_death"]



#theCsv["Lifetime_dim0"] = theCsv4["Lifetime_dim0"]
theCsv["Lifetime_dim1"] = theCsv4["Lifetime_dim1"]
theCsv["Lifetime_dim2"] =theCsv4["Lifetime_dim2"]




#theCsv["V1"] =theCsv5["V2"]
#theCsv["sd_bottle_dist_dim0"] =theCsv5["Max_life_dim1"]

#theCsv["sd_life_dim1"] =theCsv5["sd_life_dim1"]
theCsv["skew_life_dim0"] =theCsv5["skew_life_dim0"]
theCsv["skew_life_dim1"] =theCsv5["skew_life_dim1"]
theCsv["skew_life_dim2"] =theCsv5["skew_life_dim2"]

#theCsv["avg_dist_dim2"] =theCsv7["avg_dist_dim2"]
theCsv["avg_dist_dim2"] =theCsv7["sd_dist_dim1"]




#theCsv["RR_top"] 
#theCsv["RR_top"][8528] = 1000
#8528
'''
#theCsv["avg_bottle_dist_dim1"] =theCsv5["Max_life_dim0"]
#theCsv["sd_bottle_dist_dim1"] =theCsv6["V2"]

#
#theCsv["sd_bottle_dist_dim2"] =theCsv7["V2"]

#theCsv["num_dim0"] = theCsv8["x"]
#theCsv["num_dim1"] = theCsv9["x"]
#theCsv["num_dim2"] = theCsv10["x"]

#theCsv["num_dim1"] = theCsv10["x"]

#theCsv["skew_death1"] =theCsv12["skew.death.dim1"]
#theCsv["skew_death2"] =theCsv12["skew.death.dim2"]
#theCsv["skew_death0"] =theCsv12["skew.death.dim0"]


theCsv["skew_birth1"] = theCsv11["skew.birth.dim1"]
#theCsv["skew_birth2"] = theCsv11["skew.birth.dim2"]
print(len(theCsv["skew_birth1"]))

theCsv["num_per0"] = theCsv14["0"]
theCsv["num_per1"] = theCsv14["1"]
theCsv["num_per2"] = theCsv14["2"]
theCsv["num_per2"] = theCsv14["3"]



#theCsv["RR_R_mean"] = theCsv16["0"]
#print(theCsv)
#theCsv
#print(np.isnan(theCsv))

#theCsv["num_per0"][1956] = 1000
#theCsv["num_per1"][1956] = 1000
#theCsv["num_per2"][1956] = 1000
print(len(theTotal))
'''

print(theCsv)
theCsv["Normal"] = theTotal
#theCsv
#print(theCsv)
#print(theTotal)
theCsv.fillna(1000)
theCsv.replace(np.inf, 1000)

#print(np.where(theCsv.values >= np.finfo(np.float64).max))
#theCsv
#theCsv = theCsv.loc[:, ~theCsv.columns.str.contains('^Unnamed')]


#theCsv22 = theCsv.isnull().any


#for i in range(0,8529):
#    if(theCsv22["RR_top"][i] != True):
#        print(i)








#print(theCsv["RR_top"])
theCsv


               0     Mean_RR   Skew_RR  Means_dim1_birth  Means_dim1_death  \
1       9.577564  228.000000  0.124222          1.309917          1.309917   
2      87.331613  246.205882 -1.022362          0.714953          0.714953   
3      27.370830  217.387500 -3.744155          0.699906          0.699906   
4      49.270636  278.733333  0.458097          0.796660          0.796660   
5      65.337020  161.192661  1.201349          1.430684          1.430684   
6      19.667469  309.925926 -1.906248          0.477725          0.477725   
7      15.158065  286.482759 -0.421215          0.669206          0.669206   
8      47.195133  257.176471 -1.862569          0.904354          0.904354   
9      31.578818  187.577778  0.445735          1.202949          1.202949   
10      6.863423  275.809524 -0.233679          0.561889          0.561889   
11      4.524061  254.058823 -0.875039          0.795387          0.795387   
12     10.817183  267.387097 -2.427412          0.391169        

0     Mean_RR   Skew_RR  Means_dim1_birth  Means_dim1_death  \
1       9.577564  228.000000  0.124222          1.309917          1.309917   
2      87.331613  246.205882 -1.022362          0.714953          0.714953   
3      27.370830  217.387500 -3.744155          0.699906          0.699906   
4      49.270636  278.733333  0.458097          0.796660          0.796660   
5      65.337020  161.192661  1.201349          1.430684          1.430684   
6      19.667469  309.925926 -1.906248          0.477725          0.477725   
7      15.158065  286.482759 -0.421215          0.669206          0.669206   
8      47.195133  257.176471 -1.862569          0.904354          0.904354   
9      31.578818  187.577778  0.445735          1.202949          1.202949   
10      6.863423  275.809524 -0.233679          0.561889          0.561889   
11      4.524061  254.058823 -0.875039          0.795387          0.795387   
12     10.817183  267.387097 -2.427412          0.391169          0.391169   
13      6.200673  191.772727 -1.714995          1.455836          1.455836   
14     24.367191  322.200000 -0.097570          1.259250          1.259250   
15     60.248850  192.724138  0.082261          1.442371          1.442371   
16     26.584723  214.050000 -4.423269          1.397486          1.397486   
17      3.943955  120.472222 -0.331484          0.634150          0.634150   
18      9.818845  335.083333 -0.675574          0.348245          0.348245   
19     27.368149  237.369565 -2.696528          0.579889          0.579889   
20     17.515390  224.459460 -2.853643          0.783149          0.783149   
21      5.629288  281.666667 -0.195124          0.545134          0.545134   
22    123.863549  204.025641  2.792330          1.625805          1.625805   
23     30.003172  246.470588 -2.927493          0.956149          0.956149   
24     54.051054  245.205882 -2.130191          1.198832          1.198832   
25      4.790909  295.392857 -0.209853          1.247525          1.247525   
26      2.556897  309.592593 -0.233592          0.463284          0.463284   
27     35.892559  195.162791  0.701581          0.685037          0.685037   
28      2.207793  281.887097  0.098095          1.304983          1.304983   
29      5.179043  176.395833  0.968991          0.536057          0.536057   
30    100.617249  282.147541 -0.259487          1.301627          1.301627   
...          ...         ...       ...               ...               ...   
8499   22.070323  181.085106 -1.687301          0.391840          0.391840   
8500   17.770535  148.034483  0.298034          0.982664          0.982664   
8501   43.340895  278.951613  2.538419          0.791422          0.791422   
8502    9.747079  275.833333 -0.304807          0.520663          0.520663   
8503    4.875741  221.263158  0.357836          1.586060          1.586060   
8504   10.539498  225.605263 -1.840270          1.391537          1.391537   
8505   47.014478  236.833333 -2.842803          1.625233          1.625233   
8506   43.173598  290.620690 -4.902705          1.301444          1.301444   
8507    6.910835  274.047619 -0.790664          0.683359          0.683359   
8508   12.070067  258.468750 -0.391080          0.581381          0.581381   
8509   41.532710  253.060606 -3.738825          0.505467          0.505467   
8510    1.023914  173.540000 -0.778662          1.269203          1.269203   
8511    4.948677  229.324324 -3.055033          0.888330          0.888330   
8512   26.318546  288.241379 -0.349390          0.556039          0.556039   
8513   27.488561  206.293103 -3.310272          1.337732          1.337732   
8514   28.510739  190.933333  0.670719          0.926117          0.926117   
8515   15.951397  215.256410 -0.531143          0.560705          0.560705   
8516   65.512301  377.954545 -3.567989          0.545653          0.545653   
8517    7.752664  250.117647 -0.325151          1.150507          1.150507   
8518   31.350939  292.107143 -0.22976

In [386]:
### code from meduim torwards data scienec example
# Labels are the values we want to pred

labels = np.array(theCsv["Normal"])

# Remove the labels from the features
# axis 1 refers to the columns
theCsv = theCsv.drop('Normal', axis = 1)
#theCsv = theCsv.drop('AF', axis = 1)
#theCsv = theCsv.drop('Random', axis = 1)

# Saving feature names for later use
feature_list = list(theCsv.columns)

# Convert to numpy array
features = np.array(theCsv)


# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split


# Split the data into training and testing sets
train_features, test_features, train_labels, test_labels = train_test_split(theCsv, labels, test_size = 0.33, random_state = 42)


print(test_labels.tolist())

['N', 'N', 'N', 'O', 'O', 'N', 'O', 'N', 'N', 'N', 'N', 'N', 'N', 'O', 'N', '~', 'N', 'N', 'O', 'O', 'N', 'O', 'N', 'O', 'A', 'O', '~', 'N', 'N', 'O', 'N', 'O', 'N', 'N', 'O', 'O', 'N', 'N', 'N', 'N', 'N', 'N', 'O', 'N', 'O', 'A', 'N', 'N', 'N', 'A', 'N', 'O', 'N', 'N', 'A', 'N', 'N', 'N', 'N', 'O', 'N', 'O', 'N', 'O', 'A', 'O', 'O', 'N', 'N', 'N', 'N', 'O', 'N', 'N', 'N', 'N', 'N', '~', 'O', 'A', 'N', 'N', 'O', 'A', 'O', 'N', 'N', 'O', 'N', 'A', 'N', 'O', 'A', 'N', 'N', 'N', 'O', 'N', 'O', 'O', 'N', 'N', 'N', 'N', 'O', 'N', '~', 'A', 'N', 'N', 'N', 'N', '~', 'N', 'N', 'N', 'O', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'A', 'N', 'N', 'N', 'N', 'O', 'O', 'N', 'N', 'N', 'N', 'N', 'N', 'O', 'N', 'O', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'O', 'N', 'N', 'N', 'N', 'O', 'N', 'O', 'N', 'A', 'N', 'N', 'A', 'N', 'O', 'A', 'O', 'N', 'N', 'O', 'N', 'A', 'N', 'N', 'N', 'O', 'N', 'O', 'N', 'N', 'N', 'N', 'N', 'N', 'O', 'O', 'A', 'O', 'A', 'O', 'O', 'A', 'O', 'O', 'N', 'O', 'N', 'N', 'N', 'N', 'N',

In [387]:
# Import the model we are using
#from sklearn.ensemble import RandomForest
predict_list = []
# Instantiate model with 1000 decision trees
for i in range(0,1):
    #rf = RandomForestClassifier(bootstrap=True,max_depth=20,max_features="sqrt",min_samples_leaf=4,min_samples_split=10,n_estimators=50,random_state=118)
    rf = RandomForestClassifier(bootstrap=True,max_depth=10,max_features="sqrt",min_samples_leaf=1,min_samples_split=5,n_estimators=600,random_state=40)

#rf = RandomForestClassifier(bootstrap=True,max_depth=10,max_features="sqrt",min_samples_leaf=1,min_samples_split=5,n_estimators=600,random_state=42)

    

# Train the model on training data
    rf.fit(train_features, train_labels)

    predictions = rf.predict(test_features)
    predict_list.append(predictions)

In [388]:
print(predictions)

['N' 'N' 'N' ..., 'O' 'N' 'A']


In [389]:
print(test_labels)

['N' 'N' 'N' ..., 'O' 'N' 'A']


In [390]:
theMax = 0
for i in range(0,1):    
    if(accuracy_score(test_labels, predict_list[i]) > theMax):
        theMax = np.average(f1_score(test_labels, predictions, average=None))
print(theMax)

0.699275358423


In [391]:
results = confusion_matrix(test_labels, predictions,labels=["A", "N", "O","~"])
print(results)

[[ 140    2  100    3]
 [   0 1678   23    4]
 [  34   48  684    8]
 [  10   11   49   21]]


In [392]:
#print('Parameters currently in use:\n')
#print(rf.get_params())

In [393]:



var1 = 36/(29+28)
var2 = 48/(31+39)
var3 = 112/(73+66)

print((var1+var2+var3)/3)

0.7076828762553866
